export const TERMS_VERSION = 'course-20260912-v2';
export const PRIVACY_VERSION = 'course-privacy-20260912-v2';
export const PRIVACY_NOTICE = 'Autorizo el tratamiento de mi nombre, correo, teléfono, dirección, ciudad y propósito académico para gestionar la inscripción, el pago, la creación de la cuenta y la coordinación de clases. No incluye publicidad.';
export const COURSE_LEGAL_READY: boolean = true;
export const COURSE_TERMS = [
  { title: 'Quién presta las clases', text: 'Las clases se ofrecen bajo la marca WeLearn por dos profesionales independientes: José David Duarte Silva, C.C. 1.098.685.591, y Zhanna Korzh, C.E. 480.406. Domicilio contractual: Calle 47 # 29-33, Sotomayor, Bucaramanga, Colombia. El canal para solicitudes relacionadas con la inscripción, el pago o el curso es david_duarte182@hotmail.com.', highlights: ['profesionales independientes', 'José David Duarte Silva, C.C. 1.098.685.591', 'Zhanna Korzh, C.E. 480.406', 'Calle 47 # 29-33, Sotomayor, Bucaramanga, Colombia', 'david_duarte182@hotmail.com'] },
  { title: 'Tu curso y tu pago', text: 'Antes de inscribirte puedes revisar y corregir el idioma, objetivo, nivel, número de clases y precio total en pesos colombianos. Cada clase dura 100 minutos (dos sesiones de 50). El pago corresponde a un ciclo de cuatro semanas; no autoriza renovaciones ni cobros automáticos. La preparación para exámenes no incluye su inscripción ni garantiza una calificación.', highlights: ['100 minutos', 'cuatro semanas', 'no autoriza renovaciones ni cobros automáticos'] },
  { title: 'Vigencia y programación', text: 'El horario se acuerda después del pago y se confirma por escrito. Cada paquete tiene una vigencia de 28 días calendario contados desde la aprobación del pago, salvo que antes de iniciar ambas partes acuerden por escrito una fecha posterior. Todas las clases incluidas deben programarse y tomarse dentro de ese periodo. El estudiante es responsable de responder las comunicaciones y reservar oportunamente todas sus clases. Cuando los profesores hayan comunicado, por un canal verificable, suficientes opciones para completar el plan dentro del ciclo y el estudiante no programe, rechace esas opciones, no responda o deje clases pendientes, las clases no utilizadas vencen al terminar las cuatro semanas y no dan derecho a reposición, prórroga, cesión ni devolución. Esta consecuencia solo se aplica cuando los profesores tuvieron y ofrecieron disponibilidad suficiente. El pago no otorga disponibilidad ilimitada, clases adicionales ni acompañamiento permanente.', highlights: ['vigencia de 28 días calendario contados desde la aprobación del pago', 'deben programarse y tomarse dentro de ese periodo', 'vencen al terminar las cuatro semanas', 'no dan derecho a reposición, prórroga, cesión ni devolución'] },
  { title: 'Reserva del horario y asistencia', text: 'Cada clase confirmada reserva tiempo exclusivo del profesor. No se admiten cancelaciones ni cambios por decisión del estudiante; avisar con anticipación no modifica esta condición. La reprogramación se permite únicamente por una situación de salud que impida asistir, acreditada con excusa médica correspondiente a la fecha de la clase, sin perjuicio de las excepciones que exija la ley. El estudiante debe comunicar la situación tan pronto como le sea posible. La nueva fecha se acuerda según disponibilidad. Si el estudiante no asiste y no presenta esa justificación, la clase reservada se descuenta del paquete siempre que el servicio haya estado disponible en el horario acordado. La llegada tarde del estudiante no extiende la hora de finalización.', highlights: ['reserva tiempo exclusivo del profesor', 'No se admiten cancelaciones ni cambios', 'únicamente por una situación de salud', 'la clase reservada se descuenta del paquete'] },
  { title: 'Aprendizaje y convivencia', text: 'Los profesores se comprometen a impartir las clases acordadas y proporcionar los materiales previstos para el curso. El estudiante se compromete a asistir puntualmente, realizar las actividades, disponer de los materiales y mantener un trato respetuoso. En modalidad virtual debe contar con conexión y equipo adecuados. Las asignaciones se realizan de forma autónoma, en casa o en la oficina. El servicio es de enseñanza y acompañamiento académico: no garantiza alcanzar un nivel, aprobar un examen ni obtener una puntuación específica. El avance requiere asistencia, práctica y cumplimiento de las actividades.', highlights: ['asistir puntualmente', 'de forma autónoma', 'no garantiza alcanzar un nivel, aprobar un examen ni obtener una puntuación específica'] },
  { title: 'Pagos y devoluciones', text: 'No se ofrecen devoluciones comerciales por cambio de opinión, abandono del curso, falta de práctica, inasistencia o vencimiento de clases por falta de programación atribuible al estudiante. Las clases impartidas, reservadas o vencidas conforme a este reglamento se consideran al liquidar el paquete. Información legal obligatoria para compras a distancia: el retracto puede solicitarse dentro de los cinco días hábiles siguientes a la compra cuando legalmente proceda, mediante el canal de solicitudes indicado en la inscripción. La confirmación de la primera clase constituye la solicitud y autorización expresa del estudiante para iniciar el servicio; desde ese momento se aplica la excepción legal prevista para servicios cuya prestación ya comenzó. Esta información no crea devoluciones comerciales adicionales.', highlights: ['No se ofrecen devoluciones comerciales', 'cinco días hábiles', 'autorización expresa del estudiante para iniciar el servicio'] },
  { title: 'Tus datos', text: 'José David Duarte Silva y Zhanna Korzh son responsables del tratamiento de los datos usados para gestionar la inscripción, verificar el pago, crear la cuenta y coordinar el curso. Puedes presentar consultas o reclamos en david_duarte182@hotmail.com o en Calle 47 # 29-33, Sotomayor, Bucaramanga. Wompi procesa los datos del medio de pago. La autorización se presenta por separado y no incluye publicidad. No pedimos diagnósticos ni historias clínicas en este formulario. Para una reprogramación médica, el soporte debe limitarse a acreditar el impedimento y su fecha, sin diagnóstico ni historia clínica. Puedes conocer, actualizar y rectificar tus datos y solicitar prueba de la autorización, información sobre su uso, revocación o supresión cuando proceda, sin afectar los deberes legales de conservación.', highlights: ['responsables del tratamiento', 'no incluye publicidad', 'sin diagnóstico ni historia clínica', 'conocer, actualizar y rectificar tus datos'] },
  { title: 'Quién contrata', text: 'La persona que realiza la inscripción debe ser mayor de edad. Si el estudiante es menor, debe intervenir su madre, padre o representante autorizado. Los datos de estudiantes menores requieren la protección y autorizaciones correspondientes. Para aceptar el contrato, quien paga escribe su nombre completo como firma electrónica y confirma el reglamento. Conservamos la fecha, la versión y la huella del texto aceptado junto con los datos de la orden. No continúes si no tienes autorización para proporcionar los datos del estudiante.', highlights: ['debe ser mayor de edad', 'madre, padre o representante autorizado', 'nombre completo como firma electrónica', 'fecha, la versión y la huella del texto aceptado'] },
] as const;
export const COURSE_LEGAL_SNAPSHOT = JSON.stringify({ version: TERMS_VERSION, privacyVersion: PRIVACY_VERSION, privacyNotice: PRIVACY_NOTICE, sections: COURSE_TERMS });
