import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { TFNG_GUIDED_PASSAGE_ID, TFNG_INDEPENDENT_PASSAGE_ID, TFNG_LEVELS, TFNG_OPTIONS, TFNG_PASSAGES, TFNG_STORAGE_KEY } from '../src/data/practica-exams/ielts-reading-tfng-progress.ts';
const root = process.cwd();

test('guided, independent and progress passage pools remain separated', () => { const ids = new Set(TFNG_LEVELS.flatMap((level) => level.passageIds)); assert.notEqual(TFNG_GUIDED_PASSAGE_ID, TFNG_INDEPENDENT_PASSAGE_ID); assert.equal(ids.has(TFNG_GUIDED_PASSAGE_ID), false); assert.equal(ids.has(TFNG_INDEPENDENT_PASSAGE_ID), false); });
test('six source-backed passages expose thirty exact evidence-state decisions', () => { assert.equal(TFNG_PASSAGES.length, 6); assert.equal(TFNG_PASSAGES.reduce((sum, passage) => sum + passage.decisions.length, 0), 30); for (const passage of TFNG_PASSAGES) { assert.equal(passage.decisions.length, 5); assert.match(passage.sourceUrl, /^https:\/\//); assert.ok(passage.sourceNote.length > 30); for (const decision of passage.decisions) { assert.ok(TFNG_OPTIONS.includes(decision.answer)); assert.ok(decision.evidence.length > 20); } } });
test('the engine has two relationship drills followed by four full passage sets', () => { assert.equal(TFNG_LEVELS.length, 6); assert.deepEqual(TFNG_LEVELS.slice(0, 2).map((level) => level.decisionIds?.length), [4, 4]); assert.deepEqual(TFNG_LEVELS.slice(2).map((level) => level.decisionIds), [undefined, undefined, undefined, undefined]); });
test('ambiguous legacy keys are excluded rather than scaled', () => { const ids = new Set(TFNG_PASSAGES.flatMap((passage) => passage.decisions.map((decision) => decision.id))); assert.equal(ids.has('tfng-urban-trees-03'), false); assert.equal(ids.has('tfng-urban-trees-05'), false); assert.equal(ids.has('tfng-coastal-03'), false); });
test('the bank covers all six TFNG reasoning-error families', () => { assert.deepEqual(new Set(TFNG_PASSAGES.flatMap((passage) => passage.decisions.map((decision) => decision.errorCode))), new Set(['paraphrase-missed', 'opposite-not-proved', 'silence-misclassified', 'quantifier-shift', 'time-or-degree-shift', 'outside-knowledge'])); });
test('NOT GIVEN explanations identify a precise missing relationship', () => { const missing = TFNG_PASSAGES.flatMap((passage) => passage.decisions).filter((decision) => decision.answer === 'NOT GIVEN'); assert.equal(missing.length, 9); for (const decision of missing) assert.match(`${decision.evidence} ${decision.explanation}`, /no |never|absent|missing|does not|cannot|no sentence/i); });
test('storage is versioned and scoped to True False Not Given', () => assert.match(TFNG_STORAGE_KEY, /true-false-not-given:v2$/));
test('dedicated and public rewrite routes mount all three practice surfaces in English', () => { const dedicated = fs.readFileSync(path.join(root, 'src/app/(site)/practica/ielts/reading/tipos-de-preguntas/true-false-not-given/page.tsx'), 'utf8'); const publicTemplate = fs.readFileSync(path.join(root, 'src/app/(site)/practica/ielts/reading/international-question-type/[slug]/page.tsx'), 'utf8'); for (const required of ['TfngGuidedPractice', 'TfngIndependentPractice', 'TfngProgressEngine', "locale: 'en_US'"]) assert.ok(dedicated.includes(required)); for (const required of ['isTfng', 'TfngGuidedPractice', 'TfngIndependentPractice', 'TfngProgressEngine']) assert.ok(publicTemplate.includes(required)); assert.equal(dedicated.includes('Tres pasajes para entrenar evidencia exacta'), false); });
test('the practice lab requires explicit checking and closed full-set feedback', () => { const component = fs.readFileSync(path.join(root, 'src/components/exam-practice/TfngPracticeLab.tsx'), 'utf8'); for (const required of ['type="radio"', 'Check evidence state', 'feedback closed', 'Submit full set', 'Press again to reset', 'localStorage', 'not a secure Practice, Exam or proctored mode']) assert.ok(component.includes(required)); });
test('analytics load only in the canonical Vercel production environment', () => { const layout = fs.readFileSync(path.join(root, 'src/app/layout.tsx'), 'utf8'); assert.ok(layout.includes("process.env.NODE_ENV === 'production' && ENTORNO === 'production'")); });
