import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { YNNG_GUIDED_PASSAGE_ID, YNNG_INDEPENDENT_PASSAGE_ID, YNNG_LEVELS, YNNG_OPTIONS, YNNG_PASSAGES, YNNG_STORAGE_KEY } from '../src/data/practica-exams/ielts-reading-ynng-progress.ts';
const root = process.cwd();

test('guided, independent and progress writer-view pools remain separated', () => { const ids = new Set(YNNG_LEVELS.flatMap((level) => level.passageIds)); assert.notEqual(YNNG_GUIDED_PASSAGE_ID, YNNG_INDEPENDENT_PASSAGE_ID); assert.equal(ids.has(YNNG_GUIDED_PASSAGE_ID), false); assert.equal(ids.has(YNNG_INDEPENDENT_PASSAGE_ID), false); });
test('six source-backed editorial passages expose thirty writer-view decisions', () => { assert.equal(YNNG_PASSAGES.length, 6); assert.equal(YNNG_PASSAGES.reduce((sum, passage) => sum + passage.decisions.length, 0), 30); for (const passage of YNNG_PASSAGES) { assert.equal(passage.decisions.length, 5); assert.match(passage.sourceUrl, /^https:\/\//); assert.ok(passage.sourceNote.length > 40); for (const decision of passage.decisions) { assert.ok(YNNG_OPTIONS.includes(decision.answer)); assert.ok(decision.evidence.length > 20); } } });
test('the engine has two stance drills followed by four full passage sets', () => { assert.equal(YNNG_LEVELS.length, 6); assert.deepEqual(YNNG_LEVELS.slice(0, 2).map((level) => level.decisionIds?.length), [4, 4]); assert.deepEqual(YNNG_LEVELS.slice(2).map((level) => level.decisionIds), [undefined, undefined, undefined, undefined]); });
test('materially ambiguous legacy decisions stay excluded', () => { const ids = new Set(YNNG_PASSAGES.flatMap((passage) => passage.decisions.map((decision) => decision.id))); assert.equal(ids.has('ynng-station-art-07'), false); assert.equal(ids.has('ynng-uniforms-04'), false); });
test('the bank covers six YNNG attribution and stance error families', () => { assert.deepEqual(new Set(YNNG_PASSAGES.flatMap((passage) => passage.decisions.map((decision) => decision.errorCode))), new Set(['attribution-shift', 'stance-direction', 'stance-strength', 'scope-or-quantifier', 'silence-misclassified', 'outside-knowledge'])); });
test('every passage exercises all three labels without a dominant four-item run', () => { for (const passage of YNNG_PASSAGES) { const counts = Object.fromEntries(YNNG_OPTIONS.map((answer) => [answer, passage.decisions.filter((decision) => decision.answer === answer).length])); assert.ok(YNNG_OPTIONS.every((answer) => counts[answer] >= 1), `${passage.id} must include every label`); assert.ok(Math.max(...Object.values(counts)) <= 3, `${passage.id} must not telegraph one dominant label`); } });
test('NOT GIVEN feedback identifies the exact unstated writer position', () => { const missing = YNNG_PASSAGES.flatMap((passage) => passage.decisions).filter((decision) => decision.answer === 'NOT GIVEN'); assert.equal(missing.length, 8); for (const decision of missing) assert.match(`${decision.evidence} ${decision.explanation}`, /no |never|absent|missing|does not|not establish|unstated/i); });
test('storage is versioned and scoped independently from TFNG', () => { assert.match(YNNG_STORAGE_KEY, /yes-no-not-given:v2$/); assert.doesNotMatch(YNNG_STORAGE_KEY, /true-false/); });
test('dedicated and public rewrite routes mount all three YNNG surfaces', () => { const dedicated = fs.readFileSync(path.join(root, 'src/app/(site)/practica/ielts/reading/tipos-de-preguntas/yes-no-not-given/page.tsx'), 'utf8'); const publicTemplate = fs.readFileSync(path.join(root, 'src/app/(site)/practica/ielts/reading/international-question-type/[slug]/page.tsx'), 'utf8'); for (const required of ['YnngGuidedPractice', 'YnngIndependentPractice', 'YnngProgressEngine', "locale: 'en_US'"]) assert.ok(dedicated.includes(required)); for (const required of ['isYnng', 'YnngGuidedPractice', 'YnngIndependentPractice', 'YnngProgressEngine']) assert.ok(publicTemplate.includes(required)); assert.equal(dedicated.includes('Tres pasajes para evaluar'), false); });
test('the practice lab requires explicit checking and closed full-set feedback', () => { const component = fs.readFileSync(path.join(root, 'src/components/exam-practice/YnngPracticeLab.tsx'), 'utf8'); for (const required of ['type="radio"', 'Check writer view', 'feedback closed', 'Submit full set', 'Press again to reset', 'localStorage', 'not a secure Practice, Exam or proctored mode']) assert.ok(component.includes(required)); });
test('the blueprint preserves the writer-view distinction for later scaling', () => { const blueprint = fs.readFileSync(path.join(root, 'docs/ielts-reading-practice-engine-blueprint.md'), 'utf8'); for (const required of ['identify whether a view belongs to the writer', 'NO requires an opposing writer position', 'attribution shift', 'Matching Headings']) assert.ok(blueprint.includes(required)); });
