import type { EssayTypeId } from '../introduccion/introduction-data';
import { BODY_ONE_LESSONS, type BodyArchitectureBlock, type BodyOneBlock, type BodyOneExample } from '../body-1/body-one-data';

export type BodyTwoExample = BodyOneExample;

export type BodyTwoLesson = {
  id: EssayTypeId;
  shortLabel: string;
  label: string;
  signal: string;
  function: string;
  planningQuestion: string;
  trap: string;
  examples: BodyTwoExample[];
};

const blocks = (topic: string, development: string, explanation: string, example: string, link: string): BodyOneBlock[] => [
  { label: 'Second controlling idea', tone: 'claim', purpose: 'Gives Body 2 one distinct job.', text: topic },
  { label: 'Development', tone: 'paraphrase', purpose: 'Makes the second idea precise.', text: development },
  { label: 'Contrast or continuation', tone: 'development', purpose: 'Shows how this paragraph relates to the first.', text: explanation },
  { label: 'Example', tone: 'example', purpose: 'Makes the reasoning concrete without inventing a source.', text: example },
  { label: 'Link to position', tone: 'link', purpose: 'Reconnects the paragraph to the required answer.', text: link },
];

const content: Array<Array<{ paragraphJob: string; blocks: BodyOneBlock[]; commonMistake: string }>> = [
  [
    { paragraphJob: 'Add a second reason for agreement by showing how constant grade pressure can narrow students\' motivation.', blocks: blocks('A second concern is that constant grade pressure can replace curiosity with fear of failure.', 'Students may begin to choose only tasks that protect their marks instead of attempting demanding work.', 'Consequently, the system rewards caution rather than the intellectual risk needed for genuine progress.', 'For instance, a capable pupil may avoid an unfamiliar research topic because a predictable project appears safer.', 'This loss of independent motivation further supports reducing excessive emphasis on grades.'), commonMistake: 'Repeating the durable-learning argument from Body 1 instead of adding a distinct reason.' },
    { paragraphJob: 'Add a second reason for prioritising public transport by explaining its wider access benefits.', blocks: blocks('Public transport investment also gives more residents reliable access to essential opportunities.', 'Unlike new roads, shared networks serve people who cannot drive because of age, income or disability.', 'This broader access can connect whole communities to employment, education and healthcare.', 'A frequent bus route to an industrial district, for example, can make available jobs reachable without a private car.', 'Public transport therefore deserves priority not only for efficiency but also for social access.'), commonMistake: 'Returning to congestion without developing a genuinely different access argument.' },
    { paragraphJob: 'Acknowledge the funding challenge, then rebut it while maintaining support for free access.', blocks: blocks('Although universal tuition requires substantial public spending, this cost need not make the policy unworkable.', 'Funding can be directed towards tuition while students remain responsible for living expenses and optional services.', 'A targeted system of public investment can therefore expand access without removing every private contribution.', 'For example, governments may fund places at accredited institutions while limiting support for repeated or incomplete courses.', 'The financial objection is manageable and does not outweigh the case for equal academic opportunity.'), commonMistake: 'Presenting the opposing view so strongly that the essay position becomes unclear.' },
    { paragraphJob: 'Develop a second reason supporting remote work by focusing on concentration and autonomy.', blocks: blocks('Remote work can also improve performance when employees need long periods of uninterrupted concentration.', 'Workers can organise demanding tasks around their most productive hours and reduce routine office interruptions.', 'This autonomy is particularly valuable for analytical or creative work that depends on sustained attention.', 'A software designer, for example, may complete complex testing more efficiently without frequent unscheduled meetings.', 'For suitable roles, greater control over the working environment strengthens the case for home-based work.'), commonMistake: 'Claiming remote work benefits every occupation without qualification.' },
    { paragraphJob: 'Add a second reason for restrictions by explaining children\'s limited ability to recognise persuasion.', blocks: blocks('Advertising to children is also problematic because young audiences may not recognise its persuasive purpose.', 'They can interpret promotional claims as neutral information rather than carefully designed sales messages.', 'This imbalance makes it difficult for children to evaluate products with the scepticism expected of adults.', 'A colourful advert may lead a child to associate a sugary snack with health or popularity despite offering no reliable evidence.', 'Protecting children from this unequal form of persuasion provides a further justification for strict limits.'), commonMistake: 'Using emotional language without explaining why children are especially vulnerable.' },
  ],
  [
    { paragraphJob: 'Explain the opposing view on homework, then make the writer\'s preference for limits clear.', blocks: blocks('Supporters of limited homework argue that children also need time for rest, play and family life.', 'After a full school day, excessive assignments can reduce sleep and leave little space for independent interests.', 'Admittedly, brief daily practice can reinforce material that has just been taught.', 'However, its value declines when tired pupils complete long assignments mechanically rather than thinking carefully.', 'For this reason, I favour purposeful but limited homework over a compulsory daily workload.'), commonMistake: 'Explaining the second view without revealing the writer\'s own judgement.' },
    { paragraphJob: 'Explain why some people want cars retained, while keeping support for car-free centres clear.', blocks: blocks('Those who favour continued car access emphasise the needs of people with limited mobility and businesses receiving goods.', 'A complete ban may make central services harder to reach and complicate commercial deliveries.', 'Admittedly, these access needs are legitimate and cannot simply be ignored.', 'However, permits, accessible public transport and restricted delivery periods can meet them without unrestricted traffic.', 'I therefore find the case for general car access less convincing than a carefully managed car-free centre.'), commonMistake: 'Treating the two views as equally persuasive after stating a clear preference.' },
    { paragraphJob: 'Explain the case for entrance fees and state the writer\'s balanced position.', blocks: blocks('Charging visitors can provide museums with a stable source of income for conservation and staffing.', 'Ticket revenue may protect collections when public budgets are uncertain or insufficient.', 'Admittedly, this income can be valuable when public funding is uncertain.', 'However, a mixed system can preserve revenue while preventing universal fees from excluding local residents.', 'I therefore support targeted charges rather than either entirely free or fully paid admission.'), commonMistake: 'Listing funding sources without evaluating the access trade-off.' },
    { paragraphJob: 'Develop the broad-curriculum view and show why the writer prefers it.', blocks: blocks('Advocates of a broad curriculum argue that teenagers need time to discover both their abilities and interests.', 'Early specialisation can close options before students understand the consequences of that choice.', 'Admittedly, focused study may allow a learner to develop expertise more quickly.', 'However, flexibility is more valuable while academic strengths and career preferences are still developing.', 'I therefore consider breadth the stronger foundation before specialisation begins.'), commonMistake: 'Describing variety as automatically beneficial without explaining why timing matters.' },
    { paragraphJob: 'Explain the threat view of artificial intelligence and state a qualified overall judgement.', blocks: blocks('Critics warn that artificial intelligence can concentrate decision-making power and reproduce hidden bias at scale.', 'Automated systems may influence employment, credit or public services without giving affected people a clear explanation.', 'Admittedly, automation can improve speed and consistency in routine decisions.', 'However, those gains do not justify opaque outcomes that cannot be reviewed by accountable human decision-makers.', 'I therefore view AI as beneficial only when its use remains accountable to human judgement.'), commonMistake: 'Ending with a generic statement that technology has both advantages and disadvantages.' },
  ],
  [
    { paragraphJob: 'Respond to the second instruction by proposing coordinated transport and pricing measures.', blocks: blocks('Governments can reduce congestion by combining reliable alternatives with controls on unnecessary car use.', 'More frequent public transport must be introduced before drivers are charged for entering the busiest areas.', 'This sequence gives commuters a practical substitute and makes the restriction more likely to change behaviour.', 'A city could expand peak-hour rail services and then introduce a congestion fee within the central district.', 'Such coordinated measures address the transport choices that create the problem rather than merely treating delays.'), commonMistake: 'Offering a solution that does not address the causes identified in Body 1.' },
    { paragraphJob: 'Answer the second instruction with practical ways to reduce household food waste.', blocks: blocks('Household food waste can be reduced by making purchasing and storage decisions more deliberate.', 'Clear meal plans, realistic portion sizes and visible date labels help consumers use food before buying replacements.', 'These measures interrupt the cycle in which excess products are forgotten and discarded.', 'For example, a household that plans three evening meals can buy the required ingredients instead of choosing a large promotional bundle.', 'Better planning therefore directly limits the unnecessary purchasing that drives domestic waste.'), commonMistake: 'Proposing restaurant or farm policies when the question concerns households.' },
    { paragraphJob: 'Respond with solutions that make rural communities viable for younger adults.', blocks: blocks('Rural depopulation can be slowed by improving access to skilled work and essential services outside major cities.', 'Digital infrastructure, regional training and dependable transport can reduce the practical penalty of remaining in a small community.', 'Young adults are more likely to stay when they can build a career without losing access to education or healthcare.', 'A regional technology hub linked to local colleges, for instance, could create professional jobs while supporting nearby businesses.', 'Investment must therefore make rural life economically sustainable rather than simply encouraging people to remain.'), commonMistake: 'Telling young people to stay without changing the conditions that make them leave.' },
    { paragraphJob: 'Answer what schools can do by embedding accessible movement into the school day.', blocks: blocks('Schools can respond by making physical activity frequent, varied and accessible to students with different abilities.', 'Short active breaks and a wider choice of non-competitive activities can reach pupils who avoid traditional team sports.', 'Regular participation becomes more likely when movement is part of the routine rather than an occasional event.', 'A school might offer dance, walking groups and supervised fitness sessions alongside football or athletics.', 'This inclusive approach directly addresses the inactivity created by narrow or infrequent provision.'), commonMistake: 'Placing all responsibility on parents when the instruction asks what schools can do.' },
    { paragraphJob: 'Propose complementary action by businesses and consumers to reduce plastic packaging.', blocks: blocks('Businesses and consumers can reduce packaging only if both supply and demand change.', 'Companies should offer refillable or minimal-packaging options, while shoppers should favour products that use them.', 'Producer action makes alternatives available, and consumer choice gives firms a reason to expand those systems.', 'A supermarket, for example, can introduce refill stations while rewarding customers who bring reusable containers.', 'Shared responsibility is therefore more effective than expecting either group to solve the problem alone.'), commonMistake: 'Naming recycling as the only response when the task asks how use can be addressed.' },
  ],
  [
    { paragraphJob: 'Develop the principal disadvantage, then explain why the advantages still outweigh it.', blocks: blocks('The main disadvantage of home working is the loss of informal contact that supports coordination and belonging.', 'Remote employees may receive less spontaneous help and can feel detached from the wider team.', 'However, scheduled collaboration and occasional shared working days can reduce this cost without removing flexibility.', 'A company might hold one weekly team day while allowing focused tasks to be completed remotely.', 'Because the drawback can be managed, it does not outweigh the wider advantages of flexible work.'), commonMistake: 'Describing a disadvantage without returning to the required outweigh judgement.' },
    { paragraphJob: 'Develop the principal disadvantage of tourism after Body 1 has covered its benefits.', blocks: blocks('Rapid tourism growth can place severe pressure on housing, infrastructure and local environments.', 'Short-term accommodation may reduce the supply of homes, while seasonal crowds increase waste and transport demand.', 'The income generated by visitors is less valuable when residents bear these costs without effective regulation.', 'In a small coastal town, for example, rising holiday rentals may push local workers farther from their jobs.', 'Tourism policy must therefore control these impacts if the economic advantages are to remain sustainable.'), commonMistake: 'Repeating economic benefits instead of giving the opposing side a developed paragraph.' },
    { paragraphJob: 'Develop a meaningful disadvantage, then justify why digital materials still offer greater benefits.', blocks: blocks('Digital textbooks can distract students and create unequal access when devices or internet connections are unreliable.', 'A poorly designed platform may encourage switching between applications rather than sustained reading.', 'Nevertheless, schools can provide managed devices and offline materials while retaining the benefits of current, searchable content.', 'For instance, a loan programme can ensure that every pupil uses the same downloaded textbook during class and at home.', 'With adequate access controls, these manageable drawbacks do not outweigh the educational flexibility of digital resources.'), commonMistake: 'Claiming technology is inevitably distracting without considering how schools use it.' },
    { paragraphJob: 'Develop the disadvantages of living abroad after explaining its advantages.', blocks: blocks('Living abroad can also create emotional isolation and practical insecurity.', 'Migrants may be separated from family support while adapting to unfamiliar legal, linguistic and workplace systems.', 'These pressures can be especially serious during illness, unemployment or other periods when local networks matter.', 'A new employee who loses a job overseas, for example, may lack both close relatives and detailed knowledge of available assistance.', 'International mobility therefore offers valuable opportunities but also demands considerable personal resilience.'), commonMistake: 'Presenting homesickness as a single undeveloped sentence.' },
    { paragraphJob: 'Develop the disadvantages and make clear why they do not outweigh the benefits.', blocks: blocks('The decline of physical stores can reduce local employment and weaken town-centre activity.', 'When spending moves online, small retailers may lose the regular customers needed to cover rent and staffing.', 'However, local businesses can combine specialist in-person service with online ordering rather than relying on foot traffic alone.', 'A bookshop, for example, might host events while delivering purchases through its own website.', 'Although the transition is disruptive, its costs are adaptable and do not outweigh the convenience and wider choice offered online.'), commonMistake: 'Forgetting the final comparison required by “outweigh”.' },
  ],
  [
    { paragraphJob: 'Answer the second question by judging living alone as a mixed but potentially positive development.', blocks: blocks('Living alone can be positive when it reflects independence rather than unwanted isolation.', 'Managing a home encourages financial responsibility and gives adults greater control over daily routines.', 'Its value therefore depends on whether individuals also maintain supportive social connections.', 'A person may enjoy a private home while regularly participating in family, community or friendship networks.', 'Overall, the development is beneficial when autonomy is not allowed to become social disconnection.'), commonMistake: 'Continuing to explain causes instead of answering whether the development is positive or negative.' },
    { paragraphJob: 'Answer how users can judge reliability on social media.', blocks: blocks('Users can assess reliability by tracing claims to identifiable evidence and comparing them with independent sources.', 'A professional appearance or large audience does not demonstrate that a post is accurate.', 'Checking the original publisher, date and supporting documents makes manipulation easier to detect.', 'Before sharing a health claim, for example, a reader could compare it with guidance from recognised medical institutions.', 'Deliberate verification is therefore essential when social platforms remove traditional editorial filters.'), commonMistake: 'Repeating why social media is popular instead of answering the second question.' },
    { paragraphJob: 'Answer whether repeated career changes are generally beneficial.', blocks: blocks('Changing careers can be beneficial when it allows workers to transfer skills into roles that better match their abilities and values.', 'Experience from one field can provide a useful perspective rather than being wasted after a transition.', 'The benefit is strongest when the change is planned and supported by realistic training.', 'A teacher moving into educational technology, for example, can combine classroom knowledge with newly acquired design skills.', 'Career mobility is therefore generally positive when it represents purposeful development rather than repeated instability.'), commonMistake: 'Giving advantages and disadvantages without making the requested overall judgement.' },
    { paragraphJob: 'Answer who should pay for preserving historic buildings.', blocks: blocks('Preservation costs should be shared by governments, owners and the visitors or businesses that benefit from historic sites.', 'Public funding is justified when a building has broad cultural value, but private users should also maintain the property they occupy.', 'A mixed model prevents the entire burden from falling on taxpayers while protecting assets that serve the wider community.', 'A restored market hall, for instance, could receive a conservation grant while its commercial tenants fund routine maintenance.', 'Shared financing best reflects the combination of public heritage and private benefit.'), commonMistake: 'Continuing to explain why buildings matter without identifying responsible funders.' },
    { paragraphJob: 'Answer the second question by explaining effects on families and society.', blocks: blocks('Later parenthood can bring greater financial stability but may also compress the time available for family care across generations.', 'Older parents often have established careers and resources, yet they may care for young children while supporting ageing relatives.', 'This overlap can create both secure households and considerable emotional or practical pressure.', 'A couple in their forties, for example, may fund childcare at the same time as arranging assistance for elderly parents.', 'The effects are therefore mixed and depend on whether families and public services can support these overlapping responsibilities.'), commonMistake: 'Offering another cause instead of developing the requested effects.' },
  ],
];

const settings: Array<Omit<BodyTwoLesson, 'id' | 'shortLabel' | 'signal' | 'examples'>> = [
  { label: 'Opinion: add a second reason or concede and rebut', function: 'Body 2 must extend the stated position with a genuinely distinct reason, or acknowledge and rebut the strongest opposing point without weakening the thesis.', planningQuestion: 'What second idea adds new support, or what objection can I answer fairly?', trap: 'Repeating Body 1 with different vocabulary.' },
  { label: 'Discussion: explain the second view and keep your opinion visible', function: 'Body 2 normally develops the second stated view. The writer must still make the final judgement easy to identify.', planningQuestion: 'Why do reasonable people hold the second view, and how does it affect my judgement?', trap: 'Explaining both views well but hiding the writer\'s opinion.' },
  { label: 'Problem and solution: answer the corresponding second instruction', function: 'Body 2 should answer the second requested element, often solutions or measures, and connect it logically to the causes or problems analysed in Body 1.', planningQuestion: 'Which response directly addresses the cause or problem I already explained?', trap: 'Listing generic solutions that do not match Body 1.' },
  { label: 'Advantages and disadvantages: develop the other side and judge it', function: 'Body 2 develops the opposite side. When the prompt asks whether one side outweighs the other, this paragraph must make the comparison explicit.', planningQuestion: 'What is the strongest opposing effect, and how does it affect the overall balance?', trap: 'Describing the second side without making the required judgement.' },
  { label: 'Direct questions: answer the second question explicitly', function: 'Body 2 should give a direct, developed answer to the second question rather than continuing the answer from Body 1.', planningQuestion: 'What precise answer does the second question require?', trap: 'Answering the first question twice and leaving the second incomplete.' },
];

const BODY_TWO_ARCHITECTURES: Record<EssayTypeId, BodyArchitectureBlock[]> = {
  opinion: [
    { label: 'Second claim or concession', tone: 'claim', purpose: 'Adds a distinct reason or acknowledges the strongest objection.' },
    { label: 'Development', tone: 'paraphrase', purpose: 'Makes the new reason or objection precise.' },
    { label: 'Mechanism or rebuttal', tone: 'development', purpose: 'Explains the reason or limits the objection without changing position.' },
    { label: 'Illustration', tone: 'example', purpose: 'Makes the reasoning concrete.' },
    { label: 'Position link', tone: 'link', purpose: 'Returns explicitly to the thesis.' },
  ],
  discussion: [
    { label: 'Second-view sentence', tone: 'claim', purpose: 'Presents the second stated view fairly.' },
    { label: 'Development', tone: 'paraphrase', purpose: 'Explains the strongest reasoning behind that view.' },
    { label: 'Concession or contrast', tone: 'contrast', purpose: 'Acknowledges what is reasonable before evaluating the limitation.' },
    { label: 'Rebuttal or evaluation', tone: 'development', purpose: 'Answers the concession and keeps the writer\'s judgement visible.' },
    { label: 'Mini-conclusion', tone: 'link', purpose: 'Closes the comparison with a clear partial judgement.' },
  ],
  'problem-solution': [
    { label: 'Solution claim', tone: 'claim', purpose: 'Names a response that matches the earlier problem or cause.' },
    { label: 'Implementation', tone: 'paraphrase', purpose: 'Explains what people or institutions would actually do.' },
    { label: 'Mechanism', tone: 'development', purpose: 'Shows how the response addresses the cause.' },
    { label: 'Illustration', tone: 'example', purpose: 'Demonstrates the response in a plausible setting.' },
    { label: 'Expected result', tone: 'link', purpose: 'States the relevant improvement the solution should produce.' },
  ],
  'advantages-disadvantages': [
    { label: 'Opposite-side claim', tone: 'claim', purpose: 'Develops the other required advantage or disadvantage.' },
    { label: 'Effect', tone: 'paraphrase', purpose: 'Makes its consequence precise.' },
    { label: 'Comparative evaluation', tone: 'development', purpose: 'Judges its weight against the first side when required.' },
    { label: 'Illustration', tone: 'example', purpose: 'Shows the consequence in a plausible case.' },
    { label: 'Overall balance', tone: 'link', purpose: 'Makes the final balance or outweigh judgement visible.' },
  ],
  'direct-questions': [
    { label: 'Answer to Question 2', tone: 'claim', purpose: 'Answers the second direct question immediately.' },
    { label: 'Primary reason', tone: 'paraphrase', purpose: 'Gives the main reason for that answer.' },
    { label: 'Explanation', tone: 'development', purpose: 'Develops how or why the second answer is valid.' },
    { label: 'Illustration', tone: 'example', purpose: 'Makes the answer concrete.' },
    { label: 'Question 2 conclusion', tone: 'link', purpose: 'Closes the second answer and completes the task.' },
  ],
};

export const BODY_TWO_LESSONS: BodyTwoLesson[] = BODY_ONE_LESSONS.map((lesson, lessonIndex) => ({
  id: lesson.id,
  shortLabel: lesson.shortLabel,
  signal: lesson.signal,
  ...settings[lessonIndex],
  examples: lesson.examples.map((example, exampleIndex) => ({
    ...example,
    ...content[lessonIndex][exampleIndex],
    blocks: content[lessonIndex][exampleIndex].blocks.map((item, blockIndex) => ({
      ...item,
      ...BODY_TWO_ARCHITECTURES[lesson.id][blockIndex],
    })),
  })),
}));

export function bodyTwoArchitecture(essayType: EssayTypeId) {
  return BODY_TWO_ARCHITECTURES[essayType];
}

export function bodyTwoParagraph(example: BodyTwoExample) {
  return example.blocks.map((item) => item.text).join(' ');
}
