'use client';

import { useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, FilePenLine } from 'lucide-react';
import Task2OfficialReviewBlock from '../Task2OfficialReviewBlock';
import type { EssayTypeId } from '../introduccion/introduction-data';
import { ANALYSIS_BLOCKS, PROMPT_ANALYSIS_LESSONS } from './prompt-analysis-data';
import PromptAnalysisPracticeEngine from './PromptAnalysisPracticeEngine';
import PromptAnalysisWorkshop from './PromptAnalysisWorkshop';
import styles from '../introduccion/page.module.css';

export default function PromptAnalysisClient() {
  const [activeType, setActiveType] = useState<EssayTypeId>('opinion');
  const [activeExample, setActiveExample] = useState(1);
  const lesson = PROMPT_ANALYSIS_LESSONS.find((item) => item.id === activeType) ?? PROMPT_ANALYSIS_LESSONS[0];
  const example = lesson.examples[activeExample];
  const workedExample = lesson.examples[0];
  return <div lang="en" className={styles.page}><div className={styles.shell}>
    <nav className={styles.breadcrumb} aria-label="Breadcrumb"><Link href="/practica/ielts/academic/writing/task2"><ArrowLeft size={15} /> Task 2</Link><span>/</span><span>Prompt Analysis</span></nav>
    <header className={styles.hero}><p className={styles.eyebrow}>Task 2 · Build the essay · Step 1</p><h1>Decode the prompt before you build the essay</h1><p className={styles.heroLead}>Separate the topic from the instruction, preserve its scope and assign one truthful job to each paragraph. This prevents the most expensive mistake in Task 2: writing a fluent essay that answers only part of the question.</p><div className={styles.factGrid}><div className={styles.fact}><strong>5 min</strong><span>WeLearn planning target inside the 40-minute task</span></div><div className={styles.fact}><strong>5 blocks</strong><span>topic, instruction, scope, position and body route</span></div><div className={styles.fact}><strong>5 families</strong><span>pedagogical categories, not separate official tasks</span></div><div className={styles.fact}><strong>1 test</strong><span>can every paragraph be traced to the prompt?</span></div></div></header>
    <section className={styles.section}><div className={styles.sectionHeading}><p className={styles.kicker}>Official format and WeLearn strategy</p><h2>Analyse the exact instruction, not a memorised label</h2></div><Task2OfficialReviewBlock focus="Identify every required action and scope limit before planning the essay." officialFormat="IELTS Task 2 presents a point of view, argument or problem and requires a connected response of at least 250 words. The response must address the actual prompt." welearnStrategy="WeLearn maps each prompt into five visible blocks and then assigns a function to the introduction, Body 1, Body 2 and conclusion." answerCheck="A complete plan answers every instruction word, preserves the named scope and keeps the position consistent across the paragraph route." /></section>
    <section className={styles.section}><div className={styles.sectionHeading}><p className={styles.kicker}>Sentence Lego · planning blocks</p><h2>Five decisions before the first sentence</h2><p>The blocks are stable. Their content changes according to the prompt.</p></div><div className={styles.legoRow}>{ANALYSIS_BLOCKS.map((block, index) => <div key={block.label} className={`${styles.legoBlock} ${styles[block.tone]}`} style={{ animationDelay: `${index * 90}ms` }}><strong>{block.label}</strong><p>{block.text}</p></div>)}</div></section>
    <section className={styles.section}><div className={styles.sectionHeading}><p className={styles.kicker}>Five question families</p><h2>See how the paragraph route changes</h2><p>Select a family, then study one complete demonstration before analysing four new prompts yourself.</p></div><div className={styles.typeTabs} role="tablist">{PROMPT_ANALYSIS_LESSONS.map((item) => <button key={item.id} type="button" role="tab" aria-selected={item.id === activeType} className={`${styles.typeTab} ${item.id === activeType ? styles.typeTabActive : ''}`} onClick={() => { setActiveType(item.id); setActiveExample(1); }}>{item.shortLabel}</button>)}</div><article className={styles.typePanel}><div className={styles.typeIntro}><div><h3>{lesson.label}</h3><p className={styles.signal}><strong>Instruction signal:</strong> {lesson.signal}</p><div className={styles.strategyList}><p><strong>Must answer:</strong> {lesson.mustAnswer}</p><p><strong>Body 1:</strong> {lesson.bodyOne}</p><p><strong>Body 2:</strong> {lesson.bodyTwo}</p></div></div><p className={styles.trap}><strong>Common trap</strong><br />{lesson.trap}</p></div></article></section>
    <section className={styles.section}><div className={styles.sectionHeading}><p className={styles.kicker}>Watch one · then do four</p><h2>See the thinking process before you practise it</h2><p>The demonstration uses the same interface as the workshop, so every visible decision becomes an action in the next prompt.</p></div>
      <article className={`${styles.examplePanel} ${styles.workedExample}`}>
        <div className={styles.workedBadge}>Worked example · {workedExample.title}</div>
        <div className={styles.promptCard}><span>IELTS-style prompt</span><p>{workedExample.prompt}</p></div>
        <div className={styles.workshopStep}><div className={styles.stepLabel}><strong>Step 1</strong><span>Separate the prompt into three parts</span></div><div className={styles.workedStepGrid}><div><span>Topic</span><p>{workedExample.map.topic}</p><small>The central issue in a short noun phrase.</small></div><div><span>Instruction</span><p>{workedExample.map.instruction}</p><small>The action words that control the response.</small></div><div><span>Scope</span><p>{workedExample.map.scope}</p><small>The limit or obligation that must remain visible.</small></div></div></div>
        <div className={styles.workshopStep}><div className={styles.stepLabel}><strong>Step 2</strong><span>Give each paragraph one job</span></div><div className={styles.workedStepGrid}><div><span>The thesis this prompt needs</span><p>{workedExample.map.position}</p></div><div><span>Body 1</span><p>{workedExample.map.bodyRoute[0]}</p></div><div><span>Body 2</span><p>{workedExample.map.bodyRoute[1]}</p></div></div></div>
      </article>
      <div className={styles.tryDivider}><span>Now you try</span><p>The model stays hidden until you have written your own prompt map and plan.</p></div>
      <div className={styles.exampleTabs}>{lesson.examples.slice(1).map((item, offset) => { const index = offset + 1; return <button key={item.title} type="button" className={`${styles.exampleTab} ${activeExample === index ? styles.exampleTabActive : ''}`} onClick={() => setActiveExample(index)}>{String(index + 1).padStart(2, '0')} · {item.title}</button>; })}</div>
      <article className={styles.examplePanel}><div className={styles.promptCard}><span>Your IELTS-style prompt</span><p>{example.prompt}</p></div><PromptAnalysisWorkshop key={`${activeType}-${activeExample}`} type={activeType} example={example} /></article>
    </section>
    {/* `key` por tipo: sin él, cambiar de familia con una respuesta ya comprobada dejaba en
        pantalla el veredicto de la pregunta anterior sobre las opciones de la nueva. */}
    <PromptAnalysisPracticeEngine key={activeType} essayType={activeType} />
    <section className={styles.section}><div className={styles.sectionHeading}><p className={styles.kicker}>Frequently asked questions</p><h2>Plan accurately without becoming formulaic</h2></div><div className={styles.faqGrid}><article><h3>Are these five families official task names?</h3><p>No. They are WeLearn teaching categories used to notice recurring instruction patterns. The exact wording of the prompt remains the authority.</p></article><article><h3>How long should prompt analysis take?</h3><p>WeLearn uses five minutes as a planning target inside the recommended 40 minutes. It is a strategy, not an official time limit.</p></article><article><h3>Must every essay have four paragraphs?</h3><p>No. Four paragraphs are a reliable study default, while a third body paragraph remains optional.</p></article><article><h3>What makes a plan complete?</h3><p>Every instruction and scope limit has a visible home in the thesis, Body 1, Body 2 or conclusion.</p></article></div></section>
    <nav className={styles.nextLinks}><Link href="/practica/ielts/academic/writing/task2">Task 2 architecture</Link><Link href="/practica/ielts/academic/writing/task2/introduccion"><FilePenLine size={18} /> Build the introduction <ArrowRight size={16} /></Link><Link href="/practica/ielts/academic/writing/task2/tipo-ensayo">Review question-type recognition</Link></nav>
  </div></div>;
}
