'use client';

import { useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, CheckCircle2, Eye, FileCheck2, RotateCcw } from 'lucide-react';
import Task2OfficialReviewBlock from '../Task2OfficialReviewBlock';
import type { EssayTypeId } from '../introduccion/introduction-data';
import { REVIEW_LESSONS, pickDistractors } from './review-data';
import { placeFirstAsCorrect } from '@/lib/practica/shuffle-options';
import FinalReviewPracticeEngine from './FinalReviewPracticeEngine';
import styles from '../introduccion/page.module.css';

// Mismo cambio que en los demás talleres: barajado real en vez de rotación cíclica.
function rotate<T>(items: T[], seed: string, index: number) { return placeFirstAsCorrect(items, seed, index).options; }

function ReviewWorkshop({ lessonId, caseIndex }: { lessonId: EssayTypeId; caseIndex: number }) {
  const lesson = REVIEW_LESSONS.find((item) => item.id === lessonId) ?? REVIEW_LESSONS[0]; const example = lesson.cases[caseIndex];
  const [selected, setSelected] = useState(''); const [checked, setChecked] = useState(false); const [showRevision, setShowRevision] = useState(false);
  const options = useMemo(() => rotate([example.category, ...pickDistractors(lesson.layers.map((layer) => layer.label), example.category, example.issue)], `taller-review|${example.title}`, caseIndex), [caseIndex, example.category, lesson]);
  return <div className={styles.guidedWorkshop}><div className={styles.workshopHeader}><div><span>Guided review workshop</span><h3>You diagnose it before WeLearn revises it</h3></div><button type="button" className={styles.iconButton} onClick={() => { setSelected(''); setChecked(false); setShowRevision(false); }} title="Reset this workshop" aria-label="Reset this workshop"><RotateCcw size={18} /></button></div><div className={styles.workshopStep}><div className={styles.stepLabel}><strong>Step 1</strong><span>Identify the layer that needs attention first</span></div><p className={styles.paragraphJob}><strong>Draft issue:</strong> {example.issue}</p><div className={styles.optionGrid}>{options.map((option, index) => <button key={option} type="button" className={`${styles.option} ${selected === option ? styles.selected : ''} ${checked && option === example.category ? styles.correct : ''} ${checked && selected === option && option !== example.category ? styles.incorrect : ''}`} onClick={() => { setSelected(option); setChecked(false); setShowRevision(false); }}><span>{String.fromCharCode(65 + index)}</span>{option}</button>)}</div><div className={styles.workshopActions}><button type="button" onClick={() => setChecked(true)} disabled={!selected}><Eye size={17} /> Check the diagnosis</button></div>{checked && <div className={`${styles.feedback} ${selected === example.category ? styles.feedbackCorrect : styles.feedbackIncorrect}`}><CheckCircle2 size={20} /><div><strong>{selected === example.category ? 'Correct priority.' : 'Review the answer before polishing it.'}</strong><p>{example.explanation}</p></div></div>}</div><div className={`${styles.workshopStep} ${selected !== example.category || !checked ? styles.stepLocked : ''}`}><div className={styles.stepLabel}><strong>Step 2</strong><span>Compare the targeted revision</span></div>{selected === example.category && checked && <><div className={styles.workshopActions}><button type="button" onClick={() => setShowRevision(true)}><Eye size={17} /> Reveal the targeted revision</button></div>{showRevision && <div className={styles.bodyModelReveal}><span>Expert revision</span><p className={styles.paragraphJob}>{example.revision}</p><p className={styles.comparisonNote}>The revision targets the diagnosed layer. It is not an automated band score or a claim that every sentence must match this wording.</p></div>}</>}</div></div>;
}

export default function FinalReviewClient() {
  const [activeType, setActiveType] = useState<EssayTypeId>('opinion'); const [activeExample, setActiveExample] = useState(1);
  const lesson = REVIEW_LESSONS.find((item) => item.id === activeType) ?? REVIEW_LESSONS[0]; const worked = lesson.cases[0]; const example = lesson.cases[activeExample];
  return <div lang="en" className={styles.page}><div className={styles.shell}>
    <nav className={styles.breadcrumb} aria-label="Breadcrumb"><Link href="/practica/ielts/academic/writing/task2"><ArrowLeft size={15} /> Task 2</Link><span>/</span><span>Final Review</span></nav>
    <header className={styles.hero}><p className={styles.eyebrow}>Task 2 · Build the essay · Step 6</p><h1>Review an IELTS Task 2 essay before submission</h1><p className={styles.heroLead}>Check whether the essay answers the prompt before spending time polishing individual words. Review from Task Response to language control in a stable, evidence-based order.</p><div className={styles.factGrid}><div className={styles.fact}><strong>Prompt first</strong><span>missing instructions matter more than one comma</span></div><div className={styles.fact}><strong>5 layers</strong><span>answer, logic, position, cohesion and language</span></div><div className={styles.fact}><strong>5 families</strong><span>each has a decisive final check</span></div><div className={styles.fact}><strong>No auto-band</strong><span>feedback identifies decisions, not a score</span></div></div><div className={styles.heroActions}><a href="#guided-workshop">Practise diagnosis</a><a href="#practice-engine">Open the level engine</a></div></header>
    <section className={styles.section}><div className={styles.sectionHeading}><p className={styles.kicker}>Official criteria and WeLearn strategy</p><h2>Final review protects the complete response; it is not automatic marking</h2></div><Task2OfficialReviewBlock focus="Use the remaining time to verify that the response addresses every instruction, progresses logically and communicates with sufficient control." officialFormat="IELTS assesses the complete response through Task Response, Coherence and Cohesion, Lexical Resource, and Grammatical Range and Accuracy. No official rule prescribes one review checklist or a fixed review time." welearnStrategy="WeLearn reviews high-impact decisions first: instructions, position and paragraph jobs. Cohesion and sentence-level language come after the answer is secure." answerCheck="Every tick must be supported by visible evidence in the essay. This practice explains revision choices and does not award an automated band score." /></section>
    <section className={styles.section}><div className={styles.sectionHeading}><p className={styles.kicker}>Five-layer review</p><h2>Fix the answer before polishing the language</h2><p>Reviewing in this order prevents surface corrections from hiding a larger Task Response problem.</p></div><div className={styles.legoRow}>{lesson.layers.map((layer, index) => <div key={layer.label} className={`${styles.legoBlock} ${styles[layer.tone]}`}><strong>{index + 1}. {layer.label}</strong><p>{layer.question}</p></div>)}</div></section>
    <section className={styles.section}><div className={styles.sectionHeading}><p className={styles.kicker}>Five question families</p><h2>The decisive check changes with the instruction</h2></div><div className={styles.typeTabs} role="tablist">{REVIEW_LESSONS.map((item) => <button key={item.id} type="button" role="tab" aria-selected={item.id === activeType} className={`${styles.typeTab} ${item.id === activeType ? styles.typeTabActive : ''}`} onClick={() => { setActiveType(item.id); setActiveExample(1); }}>{item.shortLabel}</button>)}</div><article className={styles.typePanel}><div className={styles.typeIntro}><div><h3>{lesson.shortLabel} review</h3><p className={styles.signal}><strong>Instruction:</strong> {lesson.instruction}</p><div className={styles.strategyList}><p><strong>Decisive check:</strong> {lesson.decisiveCheck}</p></div></div><p className={styles.trap}><strong>Review rule</strong><br />Do not tick a box because the idea is “somewhere” in the essay. Point to the exact thesis, paragraph or sentence that proves it.</p></div></article></section>
    <section id="guided-workshop" className={styles.section}><div className={styles.sectionHeading}><p className={styles.kicker}>Watch one · then do four</p><h2>Study one diagnosis, then review four</h2><p>The first case demonstrates the thinking. The next four require you to choose the priority before seeing the revision.</p></div><article className={`${styles.examplePanel} ${styles.workedExample}`}><div className={styles.workedBadge}>Worked example · {worked.title}</div><div className={styles.promptCard}><span>IELTS-style prompt</span><p>{worked.prompt}</p></div><div className={styles.modelBlockGrid}><article className={styles.claim}><strong>Draft issue</strong><p>{worked.issue}</p><small>Evidence that something needs revision</small></article><article className={styles.development}><strong>{worked.category}</strong><p>{worked.explanation}</p><small>Why this is the first relevant review layer</small></article><article className={styles.link}><strong>Targeted revision</strong><p>{worked.revision}</p><small>Fixes the diagnosed issue without rewriting blindly</small></article></div></article><div className={styles.tryDivider}><span>Now you try</span><p>Choose the highest-impact review layer before revealing the expert revision.</p></div><div className={styles.exampleTabs}>{lesson.cases.slice(1).map((item, offset) => { const index = offset + 1; return <button key={item.title} type="button" className={`${styles.exampleTab} ${activeExample === index ? styles.exampleTabActive : ''}`} onClick={() => setActiveExample(index)}>{String(index + 1).padStart(2, '0')} · {item.title}</button>; })}</div><article className={styles.examplePanel}><div className={styles.promptCard}><span>Your IELTS-style prompt</span><p>{example.prompt}</p></div><ReviewWorkshop key={`${activeType}-${activeExample}`} lessonId={activeType} caseIndex={activeExample} /></article></section>
    <FinalReviewPracticeEngine essayType={activeType} />
    <section className={styles.section}><div className={styles.sectionHeading}><p className={styles.kicker}>Frequently asked questions</p><h2>Review strategically under time pressure</h2></div><div className={styles.faqGrid}><article><h3>What should I review first?</h3><p>Start with the prompt and every instruction. A missing answer cannot be repaired by better vocabulary or punctuation.</p></article><article><h3>Does this checklist predict my band?</h3><p>No. It helps you find visible revision priorities. Writing and scoring still require expert evaluation of the complete response.</p></article><article><h3>Should I rewrite whole paragraphs?</h3><p>Usually not during a final timed review. Correct the highest-impact issue that can be fixed safely without creating new contradictions.</p></article><article><h3>What if I am under 250 words?</h3><p>Task 2 requires at least 250 words. Do not add filler: identify the least-developed required idea and extend its reasoning purposefully.</p></article></div></section>
    <nav className={styles.nextLinks}><Link href="/practica/ielts/academic/writing/task2/conclusion"><FileCheck2 size={18} /> Build the conclusion</Link><Link href="/practica/ielts/academic/writing/task2/tarea-completa">Open Complete Essay Practice <ArrowRight size={16} /></Link></nav>
  </div></div>;
}
