'use client';

import { useMemo, useState } from 'react';

type Item = { level: 1 | 2 | 3; title: string; prompt: string; options: string[]; correct: number; slot: 0 | 1 | 2 | 3; explanation: string };

const ITEMS: Item[] = [
  { level: 1, title: 'Level 1 · Recognise process structure', prompt: 'A diagram shows five stages from used bottles to new products. Which overview is aligned?', options: ['It is a linear process that transforms used bottles into new products.', 'The number of bottles increased from 2000 to 2020.', 'The process compares two factories.', 'Recycling is better for society than disposal.'], correct: 0, slot: 2, explanation: 'A process overview identifies the sequence and its starting material and outcome. It does not invent time data or evaluate the process.' },
  { level: 1, title: 'Level 1 · Choose the passive form', prompt: 'Workers heat the flakes and turn them into pellets.', options: ['The flakes are heated and turned into pellets.', 'The flakes heated and turned into pellets.', 'The flakes are heating and turn into pellets.', 'The flakes were heat and turning into pellets.'], correct: 0, slot: 0, explanation: 'Academic Task 1 commonly uses the passive when the process focuses on materials rather than people.' },
  { level: 1, title: 'Level 1 · Identify the starting material', prompt: 'In a coffee-production diagram, cherries are picked, dried, processed, roasted and packed. What begins the process?', options: ['Ripe coffee cherries', 'Ground coffee in packets', 'Roasted beans', 'A finished drink'], correct: 0, slot: 3, explanation: 'The starting point is the first visible material or action. Later products, such as roasted beans or packets, cannot begin this sequence.' },
  { level: 1, title: 'Level 1 · Select a safe sequencer', prompt: 'Filtering happens before purification in a bottled-water process. Which connector expresses that order?', options: ['After filtering, the water is purified.', 'Despite filtering, the water is purified.', 'Whereas filtering, the water is purified.', 'Because filtering, the water is purified.'], correct: 0, slot: 1, explanation: 'After accurately marks that purification follows filtering. The other options either express an unsupported relationship or are grammatically incomplete.' },
  { level: 2, title: 'Level 2 · Sequence accurately', prompt: 'The stages are: drying, removing the outer layer, roasting and packaging. Which sentence keeps the order?', options: ['After the beans are roasted, they are dried in the sun.', 'The cherries are dried before their outer layers are removed.', 'Packaging takes place before the beans are roasted.', 'The outer layers are removed after the coffee is sold.'], correct: 1, slot: 1, explanation: 'The sentence accurately links the first two stages and uses before to make the order explicit.' },
  { level: 2, title: 'Level 2 · Group stages', prompt: 'A water process includes extraction, filtering, purification, bottling and distribution. Which grouping is useful?', options: ['Source and treatment can be described first, followed by packaging and delivery.', 'Every stage should be written as a separate paragraph.', 'Only the final delivery stage matters in the overview.', 'The process should be explained through personal opinions.'], correct: 0, slot: 3, explanation: 'Grouping related stages creates a readable body structure without omitting the overall sequence.' },
  { level: 2, title: 'Level 2 · Avoid an unsupported cause', prompt: 'A diagram shows bottles being washed before they are cut into flakes. Which sentence is appropriately cautious?', options: ['The bottles are washed before being cut into flakes.', 'The bottles are washed because the factory follows environmental rules.', 'The bottles are washed to make customers trust the product.', 'The bottles are washed after the finished products are sold.'], correct: 0, slot: 0, explanation: 'The diagram supports the order of washing and cutting. It does not show a motive, policy or later sales stage.' },
  { level: 2, title: 'Level 2 · Build a linked sentence', prompt: 'Which sentence combines two brick-making stages without changing the sequence?', options: ['After the clay has been crushed, it is moulded into rectangular bricks.', 'The clay is moulded before it is removed from the ground.', 'The bricks are delivered while the clay is still being excavated.', 'The clay becomes smaller because it is delivered.'], correct: 0, slot: 2, explanation: 'Crushing precedes moulding, so this is the only sentence that preserves the visual sequence and uses a controlled passive structure.' },
  { level: 3, title: 'Level 3 · Produce a complete overview', prompt: 'A brick-making process starts with clay and ends with fired bricks ready for delivery.', options: ['Overall, clay passes through preparation, shaping, drying and firing before the finished bricks are delivered.', 'Overall, the machine is the most important part of the process.', 'Overall, bricks became more popular over the period.', 'Overall, the process proves that bricks are useful.'], correct: 0, slot: 1, explanation: 'The strongest overview captures the input, the main transformations and the outcome without adding unsupported judgement.' },
  { level: 3, title: 'Level 3 · Handle a cycle', prompt: 'A bee life cycle ends with adult bees feeding the young before the sequence begins again.', options: ['Overall, the cycle moves from eggs to mature bees and then returns to the colony stage.', 'Overall, the process has a final stage and never repeats.', 'Overall, adult bees live for exactly five years.', 'Overall, the larvae are more important than the eggs.'], correct: 0, slot: 3, explanation: 'A cycle must be described as circular. The overview should show the return to the starting system rather than inventing duration or importance.' },
  { level: 3, title: 'Level 3 · Select the best detail paragraph', prompt: 'A recycling process has collection, sorting, washing, melting and manufacturing. Which detail paragraph is best organised?', options: ['Initially, used bottles are collected and sorted. They are then washed and cut into flakes before the material is melted and moulded into new products.', 'Used bottles are useful. Recycling is important. Many people recycle at home.', 'The bottles are washed. The process is interesting. The products are good.', 'First, finished products are made. Next, bottles are collected from bins.'], correct: 0, slot: 0, explanation: 'The first option groups adjacent stages, preserves their order and focuses on the evidence shown by the process.' },
  { level: 3, title: 'Level 3 · Choose a precise final sentence', prompt: 'The final water-production stage shows labelled bottles leaving in a delivery vehicle. Which sentence is most accurate?', options: ['Finally, the bottles are labelled and transported to shops.', 'Finally, the company becomes successful because the bottles are sold.', 'Finally, customers drink the water and recommend it to friends.', 'Finally, the delivery vehicle is the largest machine in the process.'], correct: 0, slot: 2, explanation: 'The visual supports labelling and delivery to shops. It does not show sales success, consumer behaviour or a comparison of machinery.' },
];

function arrange(item: Item) {
  const correctOption = item.options[item.correct];
  const distractors = item.options.filter((_, index) => index !== item.correct);
  const options = [...distractors];
  options.splice(item.slot, 0, correctOption);
  return { options, correct: item.slot };
}

export default function ProcessPracticeEngine() {
  const [level, setLevel] = useState<1 | 2 | 3>(1);
  const [index, setIndex] = useState(0);
  const [selected, setSelected] = useState<number | null>(null);
  const [checked, setChecked] = useState(false);
  const items = ITEMS.filter((item) => item.level === level);
  const current = items[index % items.length];
  const displayed = useMemo(() => arrange(current), [current]);

  function selectLevel(value: 1 | 2 | 3) { setLevel(value); setIndex(0); setSelected(null); setChecked(false); }
  function next() { setIndex((value) => (value + 1) % items.length); setSelected(null); setChecked(false); }

  return <section aria-labelledby="process-progressive-engine" style={{ marginTop: '2.5rem' }}>
    <p className="eyebrow"><span className="ink-line" />WeLearn progressive engine</p>
    <h2 id="process-progressive-engine" style={{ margin: '0 0 0.4rem', fontSize: '1.45rem' }}>Practise process writing by level</h2>
    <p style={{ margin: '0 0 1.1rem', color: 'var(--muted)', lineHeight: 1.65 }}>Start with the visual story, then control sequence and passive grammar before building a complete process overview.</p>
    <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap', marginBottom: '1rem' }}>{([1, 2, 3] as const).map((item) => <button key={item} type="button" className="btn btn-sm" aria-pressed={level === item} onClick={() => selectLevel(item)} style={{ flex: '1 1 170px', textAlign: 'left', opacity: level === item ? 1 : 0.68 }}><strong>Level {item}</strong><br /><span style={{ fontSize: '0.72rem' }}>{item === 1 ? 'Structure and passive voice' : item === 2 ? 'Order and grouping' : 'Overview and cycles'}</span></button>)}</div>
    <div className="wl-card" style={{ padding: '1.15rem', borderTop: '4px solid #0f3d8c' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', gap: '0.6rem', marginBottom: '0.85rem', flexWrap: 'wrap' }}><div><p style={{ margin: 0, color: '#0f3d8c', fontFamily: 'var(--mono)', fontSize: '0.72rem', fontWeight: 900 }}>{current.title}</p><p style={{ margin: '0.2rem 0 0', color: 'var(--muted)', fontSize: '0.82rem' }}>Exercise {index + 1} of {items.length}</p></div></div>
      <p style={{ margin: 0, padding: '0.8rem 0.9rem', borderLeft: '3px solid #0f3d8c', background: 'rgba(15,61,140,0.05)', lineHeight: 1.55, fontStyle: 'italic' }}>&ldquo;{current.prompt}&rdquo;</p>
      <div style={{ display: 'grid', gap: '0.55rem', marginTop: '0.9rem' }}>{displayed.options.map((option, optionIndex) => <button key={option} type="button" onClick={() => !checked && setSelected(optionIndex)} aria-pressed={selected === optionIndex} style={{ textAlign: 'left', padding: '0.8rem 0.9rem', borderRadius: 8, border: `1.5px solid ${checked && optionIndex === displayed.correct ? '#059669' : checked && selected === optionIndex ? '#dc2626' : selected === optionIndex ? '#0f3d8c' : 'var(--line-soft)'}`, background: checked && optionIndex === displayed.correct ? 'rgba(5,150,105,0.08)' : selected === optionIndex ? 'rgba(15,61,140,0.06)' : 'var(--bg)', color: 'var(--ink)', cursor: checked ? 'default' : 'pointer', lineHeight: 1.55 }}>{String.fromCharCode(65 + optionIndex)}. {option}</button>)}</div>
      <div style={{ display: 'flex', gap: '0.6rem', marginTop: '1rem', flexWrap: 'wrap' }}><button type="button" className="btn btn-sm" onClick={() => setChecked(true)} disabled={selected === null || checked}>{checked ? (selected === displayed.correct ? 'Correct' : 'Review the explanation') : 'Check answer'}</button>{checked && <button type="button" className="btn btn-sm" onClick={next}>Next exercise →</button>}</div>
      {checked && <div role="status" style={{ marginTop: '0.85rem', padding: '0.8rem 0.9rem', borderRadius: 8, background: selected === displayed.correct ? 'rgba(5,150,105,0.08)' : 'rgba(217,119,6,0.08)' }}><strong>{selected === displayed.correct ? 'Good work.' : 'Review the evidence.'}</strong><p style={{ margin: '0.25rem 0 0', color: 'var(--ink-2)', lineHeight: 1.55 }}>{current.explanation}</p></div>}
    </div>
  </section>;
}
