import type { DiagnosticObjectiveSkill } from '../../../lib/diagnostic/types.ts';
import type { DiagnosticBankRecord } from '../types.ts';

export const ENGLISH_DIAGNOSTIC_ADVANCED_LANGUAGE_USE_CANDIDATE_VERSION = 'en-language-use-advanced-original-draft-1';

type Skill = Extract<DiagnosticObjectiveSkill, 'grammar' | 'vocabulary'>;
type Row = readonly [
  level: 'C1' | 'C2', skill: Skill, subdomain: string, prompt: string,
  options: readonly [string, string, string], correctIndex: 0 | 1 | 2,
  rationale: string, distractorRationales: readonly [string, string],
];

const rows: readonly Row[] = [
  ['C1', 'grammar', 'sentence-structure', 'Complete the sentence: “Only after the audit ___ how incomplete the records were.”', ['did we realise', 'we realised', 'we did realised'], 0, 'A fronted restrictive phrase triggers subject–auxiliary inversion: “did we realise”.', ['The unmarked subject–verb order does not follow this fronted trigger.', 'After “did”, the lexical verb must be the base form “realise”.']],
  ['C1', 'grammar', 'focus', 'Complete the sentence: “What the committee needs ___ a clearer account of the risks.”', ['are', 'is', 'being'], 1, 'The fused relative clause functions as a singular subject and takes “is”.', ['The complement is not the grammatical controller of agreement.', 'The sentence needs a finite verb.']],
  ['C1', 'grammar', 'modality', 'Complete the inference: “The lights were off and nobody answered. They ___ home.”', ['must leave', 'should be leaving', 'may have gone'], 2, '“May have gone” expresses a possible inference about a completed past event.', ['“Must leave” expresses present obligation.', '“Should be leaving” concerns an expected action around now.']],
  ['C1', 'grammar', 'clause-compression', 'Complete the sentence: “___ the initial data, the team postponed publication.”', ['Having reviewed', 'Reviewed', 'To reviewing'], 0, 'The perfect participle marks the review as completed before the postponement by the same subject.', ['The bare past participle would imply that the team itself was reviewed.', '“To reviewing” is not a grammatical non-finite construction.']],
  ['C1', 'grammar', 'conditionals', 'Complete the sentence: “If the samples had been stored correctly, the results ___ comparable now.”', ['will be', 'would be', 'would have been yesterday'], 1, 'This mixed conditional links an unreal past condition to a present result.', ['“Will” does not express the counterfactual result.', 'The required consequence is explicitly present: “now”.']],
  ['C1', 'grammar', 'reporting', 'Complete the sentence: “The witness denied ___ the document before the meeting.”', ['to see', 'that she sees', 'having seen'], 2, '“Deny” takes a gerund clause, and the perfect form locates seeing before the denial.', ['“Deny” is not followed by a to-infinitive in this pattern.', 'The present tense does not express the earlier event appropriately.']],
  ['C1', 'grammar', 'agreement', 'Complete the sentence: “Neither the revised estimates nor the original figure ___ entirely reliable.”', ['is', 'are being', 'have'], 0, 'With “neither…nor”, agreement here follows the nearest singular noun phrase, “the original figure”.', ['The progressive changes the intended stative construction.', '“Have” neither agrees nor supplies the required adjective complement.']],
  ['C1', 'grammar', 'subjunctive', 'Complete the recommendation: “The panel insisted that each application ___ independently.”', ['is assessed', 'be assessed', 'was assessing'], 1, 'Formal mandative clauses use the base-form subjunctive “be assessed”.', ['The indicative is possible in some varieties but does not realise the tested formal mandative pattern.', 'The active progressive incorrectly makes the application the assessor.']],
  ['C1', 'grammar', 'ellipsis', 'Complete the sentence: “Mina expected the policy to reduce delays, and it appears ___.”', ['doing so', 'that did', 'to have done so'], 2, 'The perfect infinitive “to have done so” refers back to a result already observed.', ['“Appears doing” is not the required complement pattern.', 'The finite clause is malformed after “appears”.']],
  ['C1', 'grammar', 'cohesion', 'Complete the sentence: “The evidence is limited. ___, it is sufficiently consistent to justify a pilot.”', ['Nevertheless', 'For instance', 'Similarly'], 0, '“Nevertheless” signals concession between limited evidence and a justified pilot.', ['No example follows.', 'The second sentence contrasts rather than adds a similarity.']],
  ['C1', 'grammar', 'tense-aspect', 'Complete the sentence: “By the time the review ends, the team ___ the system for eighteen months.”', ['tests', 'will have been testing', 'has tested yesterday'], 1, 'The future perfect continuous expresses duration continuing up to a future reference point.', ['The simple present does not encode the future accumulated duration.', 'The present perfect cannot combine with “yesterday” or the stated future frame.']],
  ['C1', 'grammar', 'relative-clauses', 'Complete the sentence: “The figures differ from ___ was reported in the preliminary summary.”', ['which', 'that what', 'what'], 2, '“What” is a fused relative meaning “the thing that” and serves as complement of “from”.', ['“Which” lacks an antecedent here.', '“That what” duplicates the relative marking.']],

  ['C1', 'vocabulary', 'meaning', 'The chair described the change as “incremental”. It was ___.', ['introduced in small stages', 'completed without consultation', 'impossible to reverse'], 0, '“Incremental” means occurring through a series of small additions or changes.', ['Consultation is unrelated to the word’s meaning.', 'Incremental does not imply irreversibility.']],
  ['C1', 'vocabulary', 'collocation', 'Complete the sentence: “The new evidence ___ doubt on the original explanation.”', ['throws', 'casts', 'places up'], 1, 'The established collocation is “cast doubt on”.', ['“Throw doubt on” is not the standard formal collocation.', '“Place up doubt” is not idiomatic.']],
  ['C1', 'vocabulary', 'paraphrase', 'The report “stops short of” recommending a ban. What does it do?', ['It recommends an immediate ban.', 'It refuses to discuss the issue.', 'It approaches but does not make that recommendation.'], 2, 'To stop short of doing something is not to go as far as that action.', ['The phrase explicitly withholds the final step.', 'The report can discuss a ban without endorsing it.']],
  ['C1', 'vocabulary', 'register', 'Which sentence is most appropriate in a formal risk assessment?', ['The evidence warrants caution, although the probability remains uncertain.', 'The numbers look pretty scary, to be honest.', 'This whole thing could go badly wrong, you know.'], 0, 'This option is precise, measured and appropriately formal.', ['“Pretty scary” and “to be honest” are conversational and vague.', '“This whole thing” and “you know” are imprecise and informal.']],
  ['C1', 'vocabulary', 'word-formation', 'Complete the sentence: “The apparent ___ of the two measures disappeared on closer inspection.”', ['equivalent', 'equivalence', 'equivalently'], 1, 'The noun “equivalence” is required after the adjective “apparent”.', ['“Equivalent” is an adjective or count noun and does not fit this structure.', '“Equivalently” is an adverb.']],
  ['C1', 'vocabulary', 'meaning', 'A “tenuous” connection between two events is ___.', ['widely accepted', 'deliberately hidden', 'weak and insufficiently supported'], 2, '“Tenuous” describes something slight, weak or lacking a firm basis.', ['Wide acceptance does not describe evidential strength.', 'Secrecy is not part of the meaning.']],
  ['C1', 'vocabulary', 'collocation', 'Complete the sentence: “The findings are broadly ___ with earlier research.”', ['consistent', 'constant', 'consecutive'], 0, '“Consistent with” means compatible or in agreement with evidence.', ['“Constant” means unchanging.', '“Consecutive” means following in sequence.']],
  ['C1', 'vocabulary', 'paraphrase', 'The minister tried to “play down” the disagreement. She tried to ___.', ['document it in detail', 'make it seem less important', 'attribute it to another person'], 1, 'To play something down is to minimise its apparent importance or seriousness.', ['Detailed documentation may emphasise rather than minimise it.', 'Shifting blame is not the meaning of the phrasal verb.']],
  ['C1', 'vocabulary', 'meaning', 'The committee’s remit is “narrowly defined”. Its responsibilities are ___.', ['frequently changing', 'secret from the public', 'limited to a specific scope'], 2, 'A narrowly defined remit covers a restricted and specific area.', ['Frequency of change is separate from scope.', 'The phrase does not imply secrecy.']],
  ['C1', 'vocabulary', 'collocation', 'Complete the sentence: “The author ___ a distinction between correlation and cause.”', ['draws', 'paints', 'pulls'], 0, 'The conventional academic collocation is “draw a distinction”.', ['“Paint a distinction” is not idiomatic here.', '“Pull a distinction” is not the established expression.']],
  ['C1', 'vocabulary', 'connotation', 'Calling a proposal “ambitious” rather than “unrealistic” presents it as ___.', ['certain to fail', 'challenging but potentially admirable', 'minor and easily achieved'], 1, '“Ambitious” can positively frame a difficult goal without declaring it impossible.', ['“Unrealistic”, not “ambitious”, directly implies likely failure.', 'Ambitious goals are not minor or easy.']],
  ['C1', 'vocabulary', 'discourse', 'Complete the sentence: “The estimate is provisional; ___, it should not be used as a fixed target.”', ['by the same token', 'in passing', 'accordingly'], 2, '“Accordingly” introduces a consequence of the estimate being provisional.', ['“By the same token” draws a parallel rather than a direct consequence here.', '“In passing” marks an incidental comment.']],

  ['C2', 'grammar', 'inversion', 'Complete the sentence: “Had the discrepancy not been noticed, the report ___ unchanged.”', ['would have remained', 'had remained', 'would remain yesterday'], 0, 'Inverted “Had…not” replaces “If…had not” and takes a perfect conditional result.', ['A second past perfect does not express the counterfactual result.', '“Yesterday” conflicts with this malformed present conditional form.']],
  ['C2', 'grammar', 'modality', 'Complete the sentence: “I would rather the announcement ___ until the figures are verified.”', ['is delayed', 'were delayed', 'will delay'], 1, 'After “would rather” with a different subject, the past form expresses present or future preference.', ['The indicative present does not mark the required remoteness.', 'The active future incorrectly makes the announcement perform the delay.']],
  ['C2', 'grammar', 'concession', 'Complete the sentence: “___ the evidence may appear, it does not establish causation.”', ['However strongly', 'Despite strongly', 'Strong though that'], 0, '“However + adverb + subject + verb” forms a grammatical concessive clause.', ['“Despite” requires a noun phrase or gerund, not this adverbial clause.', 'The “though” construction would require “Strong though the evidence may appear”.']],
  ['C2', 'grammar', 'ellipsis', 'Complete the sentence: “The first model underestimated demand, as ___ the second.”', ['was', 'did', 'had been'], 1, 'Pro-form “did” substitutes for the past-tense verb phrase “underestimated demand”.', ['“Was” cannot substitute for that lexical verb phrase.', '“Had been” would require a compatible passive or complement.']],
  ['C2', 'grammar', 'focus', 'Complete the sentence: “It was not the conclusion itself but the confidence with which it was stated ___ concerned reviewers.”', ['what', 'where', 'that'], 2, 'A cleft construction uses “that” to link the focused phrase to the relative clause.', ['“What” would create a different fused-relative structure.', '“Where” refers to place.']],
  ['C2', 'grammar', 'clause-compression', 'Complete the sentence: “___ more narrowly, the claim would be defensible.”', ['To formulate', 'Having formulated', 'Formulated'], 2, 'The reduced passive conditional means “If the claim were formulated more narrowly”.', ['The infinitive would imply purpose and lacks a clear controller.', 'This active perfect participle would imply the claim performed the formulation.']],
  ['C2', 'grammar', 'sentence-structure', 'Complete the sentence: “At no point ___ access to the unedited data.”', ['were participants given', 'participants were given', 'did participants given'], 0, 'A fronted negative adverbial triggers inversion, and the passive phrase is “were participants given”.', ['Ordinary order is not used after this fronted negative phrase.', 'After “did”, “given” cannot form the required passive.']],
  ['C2', 'grammar', 'agreement', 'Complete the sentence: “What appear to be minor inconsistencies ___ a systematic coding error.”', ['reveals', 'reveal', 'revealing'], 1, 'The plural subject complement “minor inconsistencies” licenses plural agreement in this pseudo-cleft-like clause.', ['Singular agreement conflicts with the plural interpretation here.', 'A finite main verb is required.']],
  ['C2', 'grammar', 'tense-aspect', 'Complete the sentence: “The author ___ the distinction throughout, only to abandon it in the final chapter.”', ['maintains always', 'has been maintaining tomorrow', 'had maintained'], 2, 'The past perfect presents the sustained earlier pattern against its later abandonment.', ['The adverb position is unnatural and the present tense breaks the past narrative.', 'A future marker cannot accompany this present perfect progressive form.']],
  ['C2', 'grammar', 'relative-clauses', 'Complete the sentence: “The framework leaves open the question of by ___ authority the exception is granted.”', ['whose', 'who', 'whomsoever is'], 0, '“Whose” functions as a determiner modifying “authority” after the preposition.', ['“Who authority” is ungrammatical because a determiner is needed.', 'This form cannot modify “authority” in the clause.']],
  ['C2', 'grammar', 'correlation', 'Complete the sentence: “The more precisely the rule is defined, ___ its unexamined exceptions become.”', ['more visible', 'the more visible', 'the visible more'], 1, 'The correlative comparative requires “the more…, the more…”.', ['The second clause also requires “the”.', 'The adjective and comparative marker are in the wrong order.']],
  ['C2', 'grammar', 'counterfactuality', 'Complete the sentence: “But for the archived correspondence, the motive ___ a matter of speculation.”', ['remains yesterday', 'had remaining', 'would have remained'], 2, '“But for” introduces a counterfactual condition and the perfect result refers to the past.', ['The time expression and tense are incompatible.', 'The verb phrase is ungrammatical.']],

  ['C2', 'vocabulary', 'meaning', 'A distinction described as “specious” is ___.', ['apparently plausible but actually misleading', 'too technical for a general reader', 'supported by several independent sources'], 0, '“Specious” describes an argument or distinction that looks convincing but is unsound.', ['Technicality is not the defining feature.', 'Independent support would strengthen rather than expose it as specious.']],
  ['C2', 'vocabulary', 'collocation', 'Complete the sentence: “The exception ___ the neat opposition established earlier.”', ['dissolves away from', 'cuts across', 'moves beneath'], 1, 'To “cut across” a distinction is to resist or complicate its established boundaries.', ['“Dissolves away from” is not the relevant collocation.', '“Moves beneath” does not express conceptual complication.']],
  ['C2', 'vocabulary', 'paraphrase', 'The qualification is “anything but incidental”. It is ___.', ['mentioned only by chance', 'unrelated to the argument', 'central rather than minor'], 2, '“Anything but” emphatically negates the adjective: the qualification is not incidental.', ['The phrase denies that it is merely accidental.', 'Its non-incidental status makes it relevant, not unrelated.']],
  ['C2', 'vocabulary', 'register', 'Which sentence offers the most appropriately qualified academic claim?', ['The pattern is compatible with the proposed mechanism, although it does not uniquely identify it.', 'The pattern obviously proves what is really happening.', 'There is no way anyone could interpret these results differently.'], 0, 'This option states evidential compatibility while preserving alternative explanations.', ['“Obviously proves” overstates what a pattern can establish.', 'The absolute dismissal of alternatives is unjustified and informal.']],
  ['C2', 'vocabulary', 'word-formation', 'Complete the sentence: “The categories acquire an appearance of ___ through repeated use.”', ['inevitable', 'inevitability', 'inevitably'], 1, 'The noun “inevitability” completes the prepositional phrase after “of”.', ['“Inevitable” is an adjective.', '“Inevitably” is an adverb.']],
  ['C2', 'vocabulary', 'meaning', 'A “parsimonious” explanation accounts for the evidence with ___.', ['the most dramatic language available', 'several unrelated assumptions', 'no more assumptions than are necessary'], 2, 'In analytical contexts, “parsimonious” means economical in assumptions or explanatory machinery.', ['Rhetorical drama is irrelevant.', 'Unnecessary assumptions are the opposite of parsimony.']],
  ['C2', 'vocabulary', 'collocation', 'Complete the sentence: “The later evidence ___ the premise on which the policy rested.”', ['undermines', 'underwrites against', 'undergoes'], 0, 'Evidence can “undermine a premise” by weakening its credibility or support.', ['“Underwrite against” does not form this meaning.', '“Undergo” requires the premise to experience something and does not express weakening.']],
  ['C2', 'vocabulary', 'meaning', 'The two accounts are not “mutually exclusive”. This means they ___.', ['must both be false', 'could both be true', 'use identical wording'], 1, 'If claims are not mutually exclusive, accepting one does not require rejecting the other.', ['They may both be true, so both need not be false.', 'Logical compatibility does not require identical language.']],
  ['C2', 'vocabulary', 'connotation', 'Describing a reform as “ostensibly technical” suggests that it ___.', ['has no technical features at all', 'was designed by engineers', 'appears technical while possibly carrying other implications'], 2, '“Ostensibly” marks the stated or apparent character as potentially incomplete.', ['The word does not deny every technical feature.', 'It concerns appearance, not the profession of its designers.']],
  ['C2', 'vocabulary', 'paraphrase', 'The evidence “bears out” the earlier warning. It ___.', ['supports or confirms it', 'renders it impossible to test', 'replaces it with a stronger warning'], 0, 'To bear out a claim is to support or confirm it with evidence.', ['Confirmation improves support rather than preventing a test.', 'The expression does not mean replacement.']],
  ['C2', 'vocabulary', 'collocation', 'Complete the sentence: “The argument is ___ on a distinction the data do not support.”', ['hinged by', 'predicated', 'assembled to'], 1, '“Predicated on” means founded or based on a premise.', ['The idiom would be “hinges on”, not “is hinged by” here.', '“Assembled to” does not express logical dependence.']],
  ['C2', 'vocabulary', 'discourse', 'Complete the sentence: “The model is elegant. ___, elegance is not evidence of explanatory adequacy.”', ['Inasmuch as', 'Thereby', 'Be that as it may'], 2, '“Be that as it may” concedes the previous point before introducing a limitation.', ['“Inasmuch as” introduces degree or reason and needs a clause.', '“Thereby” introduces a result, not a concession.']],
];

export const ENGLISH_DIAGNOSTIC_ADVANCED_LANGUAGE_USE_CANDIDATES: readonly DiagnosticBankRecord[] = rows.map((row, index) => {
  const [level, skill, subdomain, prompt, options, correctIndex, rationale, distractorRationales] = row;
  const ordinal = rows.slice(0, index + 1).filter(candidate => candidate[0] === level && candidate[1] === skill).length;
  const id = `en-${level.toLowerCase()}-${skill}-${String(ordinal).padStart(2, '0')}`;
  const optionIds = options.map((_, optionIndex) => `${id}-o${optionIndex + 1}`);
  const distractorIndexes = [0, 1, 2].filter(optionIndex => optionIndex !== correctIndex);
  return {
    publicItem: {
      id, contentVersion: 'draft-1', language: 'en', skill, subdomain, levelCandidate: level, prompt,
      stimulus: { kind: 'none' }, response: { kind: 'single-choice', optionIds },
      displayOptions: options.map((text, optionIndex) => ({ id: optionIds[optionIndex], text })),
    },
    status: 'reserved', exposure: 'reserved', review: { status: 'draft' },
    scoring: { kind: 'single-choice', optionId: optionIds[correctIndex] },
    rationale: {
      key: rationale,
      distractors: Object.fromEntries(distractorIndexes.map((optionIndex, rationaleIndex) => [
        optionIds[optionIndex], distractorRationales[rationaleIndex],
      ])),
    },
    source: { kind: 'welearn-original', reference: ENGLISH_DIAGNOSTIC_ADVANCED_LANGUAGE_USE_CANDIDATE_VERSION },
    levelRange: [level, level],
    warnings: ['PENDING_INDEPENDENT_LINGUISTIC_REVIEW', 'PENDING_PILOT_CALIBRATION'],
  };
});
