import type { CefrLevel, DiagnosticObjectiveSkill } from '../../../lib/diagnostic/types.ts';
import type { DiagnosticBankRecord } from '../types.ts';

export const ENGLISH_DIAGNOSTIC_LANGUAGE_USE_CANDIDATE_VERSION = 'en-language-use-original-draft-1';
const ENGLISH_DIAGNOSTIC_LANGUAGE_USE_REVISED_VERSION = 'en-language-use-original-draft-2';

type LanguageUseSeed = {
  level: CefrLevel;
  skill: Extract<DiagnosticObjectiveSkill, 'grammar' | 'vocabulary'>;
  subdomain: string;
  prompt: string;
  options: readonly [string, string, string];
  correctIndex: 0 | 1 | 2;
  rationale: string;
  distractorRationales: readonly [string, string];
};

const lowerSeeds: readonly LanguageUseSeed[] = [
  {
    level: 'A1', skill: 'grammar', subdomain: 'form',
    prompt: 'Complete the sentence: “I ___ from Colombia.”',
    options: ['is', 'am', 'are'], correctIndex: 1,
    rationale: 'The first-person singular subject “I” takes the present form “am”.',
    distractorRationales: ['“Is” is used with he, she, or it.', '“Are” is used with you, we, or they.'],
  },
  {
    level: 'A1', skill: 'grammar', subdomain: 'agreement',
    prompt: 'Complete the sentence: “She ___ coffee every morning.”',
    options: ['drink', 'drinking', 'drinks'], correctIndex: 2,
    rationale: 'A third-person singular subject takes “-s” in the present simple: “she drinks”.',
    distractorRationales: ['The base form does not agree with “she” here.', 'The “-ing” form needs an auxiliary verb.'],
  },
  {
    level: 'A1', skill: 'grammar', subdomain: 'form',
    prompt: 'Complete the sentence: “We ___ have a car.”',
    options: ["don’t", "isn’t", "doesn’t"], correctIndex: 0,
    rationale: 'The present-simple negative with “we” is “do not”, contracted to “don’t”.',
    distractorRationales: ['“Isn’t” negates the verb “be”, not “have” in this pattern.', '“Doesn’t” is used with he, she, or it.'],
  },
  {
    level: 'A1', skill: 'grammar', subdomain: 'sentence-structure',
    prompt: 'Complete the question: “___ there a bank near here?”',
    options: ['Are', 'Is', 'Do'], correctIndex: 1,
    rationale: 'A singular noun after “there” uses the question form “Is there…?”',
    distractorRationales: ['“Are there” introduces a plural noun.', '“Do there” is not the English existential question pattern.'],
  },
  {
    level: 'A1', skill: 'grammar', subdomain: 'form',
    prompt: 'Complete the sentence: “They ___ two children.”',
    options: ['has', 'having', 'have'], correctIndex: 2,
    rationale: 'The subject “they” takes the base present form “have”.',
    distractorRationales: ['“Has” is used with he, she, or it.', '“Having” cannot serve as the finite verb without an auxiliary here.'],
  },
  {
    level: 'A1', skill: 'grammar', subdomain: 'form',
    prompt: 'Complete the answer: “Can you swim?” “Yes, I ___.”',
    options: ['can', 'do', 'am'], correctIndex: 0,
    rationale: 'A short answer repeats the modal in the question: “Yes, I can.”',
    distractorRationales: ['“Do” would answer a question formed with “do”.', '“Am” would answer a question formed with “be”.'],
  },
  {
    level: 'A1', skill: 'grammar', subdomain: 'agreement',
    prompt: 'Complete the sentence about a boy: “___ name is Luis.”',
    options: ['He', 'His', 'Him'], correctIndex: 1,
    rationale: '“His” is the possessive determiner required before the noun “name”.',
    distractorRationales: ['“He” is a subject pronoun and cannot modify “name”.', '“Him” is an object pronoun and cannot modify “name”.'],
  },
  {
    level: 'A1', skill: 'grammar', subdomain: 'agreement',
    prompt: 'Complete the sentence: “The books ___ on the table.”',
    options: ['is', 'be', 'are'], correctIndex: 2,
    rationale: 'The plural subject “books” agrees with the present form “are”.',
    distractorRationales: ['“Is” agrees with a singular subject.', 'The bare form “be” is not finite in this sentence.'],
  },
  {
    level: 'A1', skill: 'grammar', subdomain: 'sentence-structure',
    prompt: 'Complete the question: “What time ___ you start work?”',
    options: ['do', 'are', 'does'], correctIndex: 0,
    rationale: 'A present-simple question with “you” uses the auxiliary “do”.',
    distractorRationales: ['“Are” would require a different verb pattern.', '“Does” is used with he, she, or it.'],
  },
  {
    level: 'A1', skill: 'grammar', subdomain: 'agreement',
    prompt: 'Complete the sentence: “There ___ some milk in the fridge.”',
    options: ['are', 'is', 'be'], correctIndex: 1,
    rationale: 'The uncountable noun “milk” takes the singular existential form “there is”.',
    distractorRationales: ['“Are” is used with plural countable nouns.', 'The bare form “be” cannot be the finite verb here.'],
  },
  {
    level: 'A1', skill: 'grammar', subdomain: 'cohesion',
    prompt: 'Complete the sentence: “I have English class ___ Monday.”',
    options: ['at', 'in', 'on'], correctIndex: 2,
    rationale: 'English uses the preposition “on” with days of the week.',
    distractorRationales: ['“At” is normally used with clock times.', '“In” is normally used with months, years, or longer periods.'],
  },
  {
    level: 'A1', skill: 'grammar', subdomain: 'sentence-structure',
    prompt: 'Choose the sentence with the correct word order.',
    options: ['I usually walk to school.', 'I walk usually to school.', 'Usually I to school walk.'], correctIndex: 0,
    rationale: 'A frequency adverb normally comes before the main verb: “usually walk”.',
    distractorRationales: ['Placing “usually” after the main verb is not the neutral pattern here.', 'The subject, adverb, verb, and complement are in the wrong order.'],
  },
  {
    level: 'A1', skill: 'vocabulary', subdomain: 'meaning',
    prompt: 'A doctor usually works in a ___.',
    options: ['station', 'hospital', 'market'], correctIndex: 1,
    rationale: 'A hospital is the usual workplace associated with a doctor.',
    distractorRationales: ['A station is associated with transport or public services.', 'A market is a place where goods are sold.'],
  },
  {
    level: 'A1', skill: 'vocabulary', subdomain: 'meaning',
    prompt: 'Complete the sentence: “I’m thirsty. I need some ___.”',
    options: ['bread', 'music', 'water'], correctIndex: 2,
    rationale: 'Being thirsty means needing a drink, so “water” fits the context.',
    distractorRationales: ['Bread responds to hunger, not thirst.', 'Music cannot satisfy thirst.'],
  },
  {
    level: 'A1', skill: 'vocabulary', subdomain: 'meaning',
    prompt: 'Which word means the opposite of “expensive”?',
    options: ['cheap', 'heavy', 'busy'], correctIndex: 0,
    rationale: '“Cheap” contrasts with “expensive” in price.',
    distractorRationales: ['“Heavy” describes weight.', '“Busy” describes activity or availability.'],
  },
  {
    level: 'A1', skill: 'vocabulary', subdomain: 'meaning',
    prompt: 'Which item do people normally wear on their feet?',
    options: ['Gloves', 'Shoes', 'A scarf'], correctIndex: 1,
    rationale: 'Shoes are worn on the feet.',
    distractorRationales: ['Gloves are worn on the hands.', 'A scarf is worn around the neck.'],
  },
  {
    level: 'A1', skill: 'vocabulary', subdomain: 'collocation',
    prompt: 'Complete the phrase: “___ a shower”.',
    options: ['Make', 'Put', 'Take'], correctIndex: 2,
    rationale: 'The standard collocation is “take a shower”.',
    distractorRationales: ['English does not normally say “make a shower” for this activity.', '“Put a shower” does not express the activity.'],
  },
  {
    level: 'A1', skill: 'vocabulary', subdomain: 'paraphrase',
    prompt: 'The weather is “freezing”. What does that mean?',
    options: ['It is very cold.', 'It is quite sunny.', 'It is very windy.'], correctIndex: 0,
    rationale: 'In everyday weather language, “freezing” means extremely cold.',
    distractorRationales: ['Sunshine and temperature are different properties.', 'Windy describes moving air, not necessarily low temperature.'],
  },
  {
    level: 'A1', skill: 'vocabulary', subdomain: 'register',
    prompt: 'Which greeting is natural when you meet a friend?',
    options: ['Goodbye, Maria', 'Hello, Maria', 'Listen, Maria'], correctIndex: 1,
    rationale: '“Hello, Maria” is a natural greeting when meeting a friend.',
    distractorRationales: ['This is a farewell, not a greeting when two friends meet.', 'This asks Maria to listen rather than greeting her.'],
  },
  {
    level: 'A1', skill: 'vocabulary', subdomain: 'word-formation',
    prompt: 'A person who teaches students is a ___.',
    options: ['teach', 'teaching', 'teacher'], correctIndex: 2,
    rationale: 'The suffix “-er” forms the person noun “teacher” from the verb “teach”.',
    distractorRationales: ['“Teach” is a verb, not the person noun needed after “a”.', '“Teaching” names an activity and does not fit after “a” here.'],
  },
  {
    level: 'A1', skill: 'vocabulary', subdomain: 'paraphrase',
    prompt: 'A sign says, “The shop is closed.” What does it mean?',
    options: ['You cannot shop there now.', 'Everything is free today.', 'The shop moved upstairs.'], correctIndex: 0,
    rationale: 'A closed shop is not open for customers at that time.',
    distractorRationales: ['“Closed” says nothing about prices.', '“Closed” does not mean that the location changed.'],
  },
  {
    level: 'A1', skill: 'vocabulary', subdomain: 'meaning',
    prompt: 'If you “borrow” a book, what do you do?',
    options: ['Write a new copy', 'Take it and return it later', 'Give it away forever'], correctIndex: 1,
    rationale: 'To borrow something is to take it for a time with the intention of returning it.',
    distractorRationales: ['Borrowing does not mean copying or writing.', 'Giving something away transfers it permanently.'],
  },
  {
    level: 'A1', skill: 'vocabulary', subdomain: 'collocation',
    prompt: 'Complete the phrase: “___ the bus to work”.',
    options: ['Do', 'Drive', 'Take'], correctIndex: 2,
    rationale: 'The normal travel collocation is “take the bus”.',
    distractorRationales: ['English does not say “do the bus”.', 'A passenger takes a bus; “drive” would identify the driver.'],
  },
  {
    level: 'A1', skill: 'vocabulary', subdomain: 'register',
    prompt: 'Which question asks for the price of an item?',
    options: ['How much is this?', 'How old is this?', 'How far is this?'], correctIndex: 0,
    rationale: '“How much” asks about price or quantity; here it asks the item’s price.',
    distractorRationales: ['“How old” asks about age.', '“How far” asks about distance.'],
  },
  {
    level: 'A2', skill: 'grammar', subdomain: 'tense-aspect',
    prompt: 'Complete the sentence: “Last night, we ___ dinner at home.”',
    options: ['eat', 'ate', 'eating'], correctIndex: 1,
    rationale: '“Last night” locates a completed event in the past, so the irregular past form “ate” is required.',
    distractorRationales: ['“Eat” is the base or present form.', '“Eating” requires an auxiliary and cannot stand alone here.'],
  },
  {
    level: 'A2', skill: 'grammar', subdomain: 'sentence-structure',
    prompt: 'Complete the question: “Where did your sister ___ yesterday?”',
    options: ['went', 'going', 'go'], correctIndex: 2,
    rationale: 'After the past auxiliary “did”, English uses the base form “go”.',
    distractorRationales: ['The past is already marked by “did”, so “went” would mark it twice.', 'The “-ing” form does not follow “did” in this question.'],
  },
  {
    level: 'A2', skill: 'grammar', subdomain: 'tense-aspect',
    prompt: 'Complete the sentence: “Look! The children ___ in the garden.”',
    options: ['are playing', 'play', 'played'], correctIndex: 0,
    rationale: '“Look!” signals an action happening now, expressed by the present continuous “are playing”.',
    distractorRationales: ['The present simple normally describes habits or repeated events.', 'The past form places the action before now.'],
  },
  {
    level: 'A2', skill: 'grammar', subdomain: 'form',
    prompt: 'Complete the comparison: “This film is ___ than the first one.”',
    options: ['most interesting', 'more interesting', 'interestingly'], correctIndex: 1,
    rationale: 'A multi-syllable adjective forms the comparative with “more”, and “than” confirms the comparison.',
    distractorRationales: ['“Most interesting” is a superlative and normally needs “the”.', '“Interestingly” is an adverb, not the adjective complement needed here.'],
  },
  {
    level: 'A2', skill: 'grammar', subdomain: 'form',
    prompt: 'Complete the sentence: “Marta is ___ person in her family.”',
    options: ['taller', 'more tall', 'the tallest'], correctIndex: 2,
    rationale: 'Comparing one person with the whole family requires the superlative “the tallest”.',
    distractorRationales: ['“Taller” compares two people and would normally be followed by “than”.', 'The regular comparative of “tall” is “taller”, not “more tall”.'],
  },
  {
    level: 'A2', skill: 'grammar', subdomain: 'agreement',
    prompt: 'Complete the question: “How ___ rice do we need?”',
    options: ['much', 'many', 'several'], correctIndex: 0,
    rationale: '“Rice” is uncountable in this context, so quantity is asked with “how much”.',
    distractorRationales: ['“Many” is used with plural countable nouns.', '“How several” is not a grammatical quantity question.'],
  },
  {
    level: 'A2', skill: 'grammar', subdomain: 'tense-aspect',
    prompt: 'Complete the plan: “Sara ___ her aunt this weekend.”',
    options: ['visited', 'is visiting', 'has visit'], correctIndex: 1,
    rationale: 'The present continuous “is visiting” expresses Sara’s arranged future plan for the coming weekend.',
    distractorRationales: ['The simple past conflicts with the future time expression.', 'The present perfect requires the participle “visited”.'],
  },
  {
    level: 'A2', skill: 'grammar', subdomain: 'tense-aspect',
    prompt: 'Complete the sentence: “I ___ my homework, so I can go out now.”',
    options: ['have finish', 'am finished', 'have finished'], correctIndex: 2,
    rationale: 'The present perfect “have finished” connects a completed action with its present result.',
    distractorRationales: ['The present perfect requires the participle “finished”.', 'The passive-like form does not express completing the homework.'],
  },
  {
    level: 'A2', skill: 'grammar', subdomain: 'form',
    prompt: 'A friend has a headache. Choose the best advice.',
    options: ['You should rest for a while.', 'You must to resting now.', 'You should to take a rest.'], correctIndex: 0,
    rationale: 'The modal “should” is followed by the base verb and appropriately expresses advice.',
    distractorRationales: ['A modal is not followed by “to” or an “-ing” form here.', 'English uses “should take”, without “to”.'],
  },
  {
    level: 'A2', skill: 'grammar', subdomain: 'cohesion',
    prompt: 'Complete the sentence: “If it rains tomorrow, we ___ at home.”',
    options: ['stayed', 'will stay', 'would staying'], correctIndex: 1,
    rationale: 'A likely future condition uses present simple after “if” and “will” in the result clause.',
    distractorRationales: ['“Stayed” places the result in the past.', '“Would staying” is not a grammatical verb phrase.'],
  },
  {
    level: 'A2', skill: 'grammar', subdomain: 'cohesion',
    prompt: 'Complete the sentence: “The woman ___ works at the library is my neighbour.”',
    options: ['which', 'where', 'who'], correctIndex: 2,
    rationale: 'The relative pronoun “who” refers to a person and functions as the subject of “works”.',
    distractorRationales: ['“Which” normally refers to things.', '“Where” refers to places, not people.'],
  },
  {
    level: 'A2', skill: 'grammar', subdomain: 'sentence-structure',
    prompt: 'Complete the sentence: “My brother enjoys ___ new recipes.”',
    options: ['trying', 'to tried', 'try'], correctIndex: 0,
    rationale: 'The verb “enjoy” is followed by an “-ing” form: “enjoys trying”.',
    distractorRationales: ['“To tried” combines incompatible infinitive and past forms.', 'The bare verb does not normally follow “enjoy”.'],
  },
  {
    level: 'A2', skill: 'vocabulary', subdomain: 'meaning',
    prompt: 'Where would you normally go to buy medicine?',
    options: ['A bakery', 'A pharmacy', 'A library'], correctIndex: 1,
    rationale: 'A pharmacy is a shop that prepares or sells medicine.',
    distractorRationales: ['A bakery sells bread and similar food.', 'A library lends books and other information resources.'],
  },
  {
    level: 'A2', skill: 'vocabulary', subdomain: 'meaning',
    prompt: 'The train is “delayed”. What has happened?',
    options: ['It left ahead of time.', 'It changed its destination.', 'It will arrive later than planned.'], correctIndex: 2,
    rationale: 'A delayed service happens later than its scheduled time.',
    distractorRationales: ['Leaving early is the opposite of a delay.', 'A destination change is a diversion, not necessarily a delay.'],
  },
  {
    level: 'A2', skill: 'vocabulary', subdomain: 'paraphrase',
    prompt: 'If a person is “available” this afternoon, what does it mean?',
    options: ['They are free to meet.', 'They are travelling abroad.', 'They are feeling unwell.'], correctIndex: 0,
    rationale: 'In a scheduling context, “available” means free and able to meet.',
    distractorRationales: ['Travel is not implied by availability.', 'Health is not implied by availability.'],
  },
  {
    level: 'A2', skill: 'vocabulary', subdomain: 'collocation',
    prompt: 'Complete the phrase: “___ a mistake”.',
    options: ['Do', 'Make', 'Build'], correctIndex: 1,
    rationale: 'The standard English collocation is “make a mistake”.',
    distractorRationales: ['English does not normally say “do a mistake”.', '“Build” is used for constructing things, not errors.'],
  },
  {
    level: 'A2', skill: 'vocabulary', subdomain: 'word-formation',
    prompt: 'Complete the sentence: “Please carry the glass ___.”',
    options: ['care', 'careful', 'carefully'], correctIndex: 2,
    rationale: 'The adverb “carefully” modifies how the action “carry” should be performed.',
    distractorRationales: ['“Care” is a noun or verb and cannot directly modify “carry” here.', '“Careful” is an adjective and would describe a noun or follow “be”.'],
  },
  {
    level: 'A2', skill: 'vocabulary', subdomain: 'paraphrase',
    prompt: '“Could you look after my cat?” What is the speaker asking?',
    options: ['Take care of the cat', 'Search behind the cat', 'Buy a different cat'], correctIndex: 0,
    rationale: 'The phrasal verb “look after” means take care of a person or animal.',
    distractorRationales: ['The phrase is not a literal instruction about where to look.', 'No purchase or replacement is requested.'],
  },
  {
    level: 'A2', skill: 'vocabulary', subdomain: 'register',
    prompt: 'Which request is suitable in a polite email to a course office?',
    options: ['Send me the course dates immediately.', 'I would appreciate the course dates.', 'I want the course dates today.'], correctIndex: 1,
    rationale: '“I would appreciate…” makes the request appropriately polite for an office email.',
    distractorRationales: ['The imperative sounds too direct for this context.', 'The direct statement of desire sounds abrupt in this context.'],
  },
  {
    level: 'A2', skill: 'vocabulary', subdomain: 'meaning',
    prompt: 'At a railway station, what is a “platform”?',
    options: ['The place where passengers buy a ticket', 'The place where passengers store their bags', 'The place where passengers board a train'], correctIndex: 2,
    rationale: 'A railway platform is the raised area beside the track where passengers board and leave trains.',
    distractorRationales: ['Tickets are normally bought at a ticket office or machine.', 'Bag storage is usually called left luggage or a locker area.'],
  },
  {
    level: 'A2', skill: 'vocabulary', subdomain: 'meaning',
    prompt: 'There is a “leak” under the kitchen sink. What is happening?',
    options: ['Water is escaping from a pipe.', 'The sink is completely dry.', 'Someone is cleaning the floor.'], correctIndex: 0,
    rationale: 'A leak is an unintended escape of liquid or gas, here water from the plumbing.',
    distractorRationales: ['A dry sink provides no evidence of leaking water.', 'Cleaning may involve water but is not described by “leak”.'],
  },
  {
    level: 'A2', skill: 'vocabulary', subdomain: 'paraphrase',
    prompt: 'After walking all day, Nina was “exhausted”. How did she feel?',
    options: ['Slightly bored', 'Very tired', 'Quite surprised'], correctIndex: 1,
    rationale: '“Exhausted” means extremely tired, which fits the long day of walking.',
    distractorRationales: ['Boredom concerns interest, not physical energy.', 'Surprise is an emotional reaction, not fatigue.'],
  },
  {
    level: 'A2', skill: 'vocabulary', subdomain: 'paraphrase',
    prompt: 'The outdoor concert was “cancelled”. What does that mean?',
    options: ['It started earlier.', 'It moved to a larger place.', 'It will not take place.'], correctIndex: 2,
    rationale: 'A cancelled event has been called off and will not happen as planned.',
    distractorRationales: ['An earlier start is a schedule change, not a cancellation.', 'Changing venue does not mean cancelling the event.'],
  },
  {
    level: 'A2', skill: 'vocabulary', subdomain: 'collocation',
    prompt: 'The music is too loud. Which request fits the situation?',
    options: ['Could you turn it down?', 'Could you take it off?', 'Could you put it away?'], correctIndex: 0,
    rationale: '“Turn it down” means reduce the volume of sound or a device.',
    distractorRationales: ['“Take it off” usually means remove clothing or detach something.', '“Put it away” means return something to storage.'],
  },
];

const upperSeedRows = [
  ['B1', 'grammar', 'tense-aspect', 'Complete the sentence: “I have lived here ___ 2021.”', ['for', 'since', 'during'], 1,
    '“Since” introduces the point in time when the continuing situation began.', ['“For” introduces a duration, not a starting year.', '“During” locates an event within a period but does not mark the start of a continuing state.']],
  ['B1', 'grammar', 'tense-aspect', 'Complete the sentence: “While I was cooking, the phone ___.”', ['was ringing', 'has rung', 'rang'], 2,
    'The past simple “rang” presents the shorter completed event that interrupted the ongoing action.', ['The repeated continuous form would make both events background actions.', 'The present perfect does not combine naturally with this finished past-time frame.']],
  ['B1', 'grammar', 'cohesion', 'Complete the sentence: “If the weather improves, we ___ the match outside.”', ['will play', 'would play', 'played'], 0,
    'A real future condition uses present simple in the if-clause and “will” in the result.', ['“Would” normally marks a hypothetical result.', 'The past form does not express the expected future result.']],
  ['B1', 'grammar', 'cohesion', 'Complete the sentence: “If I had more free time, I ___ another language.”', ['will learn', 'would learn', 'learned'], 1,
    'The hypothetical present condition takes “would” plus the base verb in the result clause.', ['“Will” does not match the remote condition “if I had”.', 'A simple past result does not complete this conditional pattern.']],
  ['B1', 'grammar', 'form', 'Complete the sentence: “These bicycles ___ in a local factory.”', ['make', 'are making', 'are made'], 2,
    'The present passive “are made” focuses on the bicycles that receive the action.', ['The active base form lacks a subject that performs the action.', 'The present continuous active would mean the bicycles perform the making.']],
  ['B1', 'grammar', 'sentence-structure', 'Maya said, “I need a break.” Choose the reported statement.', ['Maya said that she needed a break.', 'Maya said that I need a break.', 'Maya said she needs yesterday a break.'], 0,
    'The pronoun and tense shift appropriately when Maya’s earlier statement is reported.', ['“I” would refer to the reporter rather than Maya.', 'The word order and time expression are not grammatical.']],
  ['B1', 'grammar', 'sentence-structure', 'Complete the sentence: “The colleague ___ helped me is from Peru.”', ['which', 'who', 'where'], 1,
    '“Who” refers to a person and serves as the subject of “helped”.', ['“Which” normally refers to things.', '“Where” refers to a place, not a person.']],
  ['B1', 'grammar', 'tense-aspect', 'Complete the sentence: “We ___ near the coast, but we moved inland.”', ['were use to live', 'use living', 'used to live'], 2,
    '“Used to” plus the base verb describes a past state that is no longer true.', ['The auxiliary and form are incorrectly combined.', '“Use living” is not the required past-habit construction.']],
  ['B1', 'grammar', 'form', 'Complete the sentence: “I enjoy ___ new recipes at weekends.”', ['trying', 'to tried', 'try'], 0,
    'The verb “enjoy” is followed by a gerund, here “trying”.', ['An infinitive marker cannot be followed by the past form.', 'The bare infinitive does not normally follow “enjoy”.']],
  ['B1', 'grammar', 'agreement', 'Complete the sentence: “You sent the form yesterday, ___?”', ['did you', 'didn’t you', 'haven’t you'], 1,
    'A positive past-simple statement takes the negative past tag “didn’t you?”.', ['The tag should reverse polarity and therefore be negative.', 'The present-perfect auxiliary does not match “sent”.']],
  ['B1', 'grammar', 'form', 'The office lights are off and the door is locked. Sam ___ be here.', ['should', 'can', 'can’t'], 2,
    'The evidence supports the strong negative deduction expressed by “can’t be”.', ['“Should be” expresses expectation, not the conclusion supported here.', 'Affirmative “can be” expresses possibility, not a strong deduction.']],
  ['B1', 'grammar', 'cohesion', 'Choose the sentence that uses “despite” correctly.', ['Despite the heavy rain, the event continued.', 'Despite it rained heavily, the event continued.', 'Despite of the heavy rain, the event continued.'], 0,
    '“Despite” can be followed directly by the noun phrase “the heavy rain”.', ['A finite clause needs “although” or the form “despite the fact that”.', 'Standard English does not use “despite of”.']],

  ['B1', 'vocabulary', 'collocation', 'Complete the sentence: “Everyone must ___ responsibility for checking the figures.”', ['make', 'take', 'do'], 1,
    'The established collocation is “take responsibility”.', ['English does not normally say “make responsibility”.', 'English does not normally say “do responsibility”.']],
  ['B1', 'vocabulary', 'paraphrase', 'The meeting was “put off” until Friday. What happened?', ['It was made shorter.', 'It was moved outside.', 'It was postponed.'], 2,
    '“Put off” means postpone an event until a later time.', ['The phrase says nothing about duration.', 'The particle does not indicate a change of location.']],
  ['B1', 'vocabulary', 'meaning', 'A “reliable” bus service is one that ___.', ['usually operates as expected', 'is always the cheapest', 'only runs at night'], 0,
    '“Reliable” describes something that can be trusted to work or happen as expected.', ['Price and reliability are different qualities.', 'The time of operation does not define reliability.']],
  ['B1', 'vocabulary', 'meaning', 'After several delays, the package “eventually” arrived. When did it arrive?', ['Immediately', 'In the end', 'By accident'], 1,
    '“Eventually” means after some time or difficulties, in the end.', ['The delays rule out immediate arrival.', 'The adverb concerns timing, not whether something was intentional.']],
  ['B1', 'vocabulary', 'meaning', 'A water “shortage” means that ___.', ['the water tastes unusual', 'water is being tested', 'there is not enough water'], 2,
    'A shortage is a situation in which the available amount is insufficient.', ['Taste is unrelated to quantity.', 'Testing does not itself imply insufficient supply.']],
  ['B1', 'vocabulary', 'collocation', 'Complete the sentence: “The team has ___ good progress this month.”', ['made', 'done', 'taken'], 0,
    'The standard collocation is “make progress”.', ['“Do progress” is not the standard expression.', '“Take progress” is not the standard expression.']],
  ['B1', 'vocabulary', 'register', 'Which opening is most suitable for a polite complaint to a hotel?', ['Your hotel was terrible. Fix this.', 'I am writing to report a problem with my room.', 'Hey, you gave me a bad room.'], 1,
    'This opening states the purpose clearly in a neutral, appropriately formal register.', ['The accusation and command are unnecessarily aggressive.', 'The greeting and wording are too casual and confrontational.']],
  ['B1', 'vocabulary', 'word-formation', 'Complete the sentence: “The road is narrow, so overtaking here is ___.”', ['danger', 'dangerously', 'dangerous'], 2,
    'The adjective “dangerous” is required after the linking verb “is”.', ['“Danger” is a noun.', '“Dangerously” is an adverb and does not serve as the subject complement here.']],
  ['B1', 'vocabulary', 'paraphrase', 'We “ran out of” printer paper. What does this mean?', ['We used all the paper.', 'We carried the paper outside.', 'We found extra paper.'], 0,
    'To run out of something is to use the available supply completely.', ['The phrase is not a literal description of movement.', 'Finding more is the opposite of having none left.']],
  ['B1', 'vocabulary', 'meaning', 'Lena was “reluctant” to speak first. How did she feel?', ['Eager to begin', 'Unwilling or hesitant', 'Unable to hear'], 1,
    '“Reluctant” means not willing and often hesitant to act.', ['Eagerness is the opposite attitude.', 'The word describes willingness, not hearing ability.']],
  ['B1', 'vocabulary', 'collocation', 'Complete the sentence: “We moved abroad but still ___ with our old neighbours.”', ['make contact in', 'hold the touching', 'keep in touch'], 2,
    '“Keep in touch” means continue communicating with someone.', ['This preposition and noun combination is not idiomatic here.', 'This is an incorrect literal rendering, not the communication idiom.']],
  ['B1', 'vocabulary', 'meaning', 'An “affordable” apartment is one that ___.', ['costs no more than you can reasonably pay', 'has walls that were painted very recently', 'stands in a neighbourhood outside the city'], 0,
    '“Affordable” means reasonably priced relative to what someone can pay.', ['Decoration does not determine affordability.', 'Location may affect price but is not the meaning of the word.']],

  ['B2', 'grammar', 'tense-aspect', 'Complete the sentence: “By next June, she ___ the training programme.”', ['completes', 'will have completed', 'has completed'], 1,
    'The future perfect marks completion before the specified future deadline.', ['The present simple does not express completion by a future point here.', 'The present perfect cannot normally be anchored by “by next June”.']],
  ['B2', 'grammar', 'cohesion', 'Complete the sentence: “If they had checked the map, they ___ lost.”', ['would not get', 'did not get', 'would not have got'], 2,
    'A past unreal condition takes “would have” plus a past participle in the result.', ['This form describes a present or future hypothetical result.', 'The past simple does not express the counterfactual consequence.']],
  ['B2', 'grammar', 'form', 'You knew the deadline had changed. You ___ me earlier.', ['should have told', 'should tell yesterday', 'must have tell'], 0,
    '“Should have told” expresses criticism of an action that did not happen in the past.', ['“Yesterday” does not combine with this unshifted modal form.', 'A perfect modal requires the past participle “told”.']],
  ['B2', 'grammar', 'sentence-structure', 'Complete the report: “The painting is believed ___ during the 1920s.”', ['to have created', 'to have been created', 'to have been creating'], 1,
    'The passive reporting pattern “is believed to have been created” refers to an earlier creation.', ['The active infinitive would make the painting the creator.', 'The active progressive would make the painting perform an ongoing creation.']],
  ['B2', 'grammar', 'form', 'Complete the sentence: “We had the heating system ___ before winter.”', ['repairing', 'to repair', 'repaired'], 2,
    'The causative pattern “have something done” takes a past participle.', ['The “-ing” form does not express the completed service.', 'The infinitive is not used after the object in this causative pattern.']],
  ['B2', 'grammar', 'tense-aspect', 'Complete the sentence: “I wish I ___ more carefully before accepting the offer.”', ['had thought', 'would think yesterday', 'have thought'], 0,
    '“Wish” plus the past perfect expresses regret about an earlier decision.', ['This form is incompatible with the past regret and the time expression.', 'The present perfect does not mark the counterfactual earlier action after “wish”.']],
  ['B2', 'grammar', 'sentence-structure', 'Complete the sentence: “The researcher ___ article we discussed will speak tonight.”', ['who', 'whose', 'which'], 1,
    '“Whose” expresses the possessive relationship between the researcher and the article.', ['“Who” cannot directly modify the noun “article”.', '“Which” would refer to a thing and does not express possession here.']],
  ['B2', 'grammar', 'sentence-structure', 'Choose the correctly reported question: Ana asked, “Why did the plan fail?”', ['Ana asked why did the plan fail.', 'Ana asked why the plan did fail.', 'Ana asked why the plan had failed.'], 2,
    'An indirect question uses statement word order, and the earlier event may shift to the past perfect.', ['Indirect questions do not retain auxiliary-before-subject order.', 'This keeps an unnecessary emphatic auxiliary and fails to backshift the earlier event.']],
  ['B2', 'grammar', 'cohesion', 'Choose the sentence with the correct concessive phrase.', ['Despite having little time, we completed the review.', 'Despite we had little time, we completed the review.', 'Despite of having little time, we completed the review.'], 0,
    '“Despite” can introduce the gerund phrase “having little time”.', ['A finite clause after “despite” requires “the fact that”.', 'Standard usage does not add “of” after “despite”.']],
  ['B2', 'grammar', 'form', 'Complete the sentence: “It was ___ useful advice that I saved the message.”', ['so', 'such', 'such a'], 1,
    '“Such” directly modifies the uncountable noun phrase “useful advice”.', ['“So” would modify an adjective or adverb without the noun in this pattern.', 'The article “a” cannot precede the uncountable noun “advice”.']],
  ['B2', 'grammar', 'cohesion', 'Complete the sentence: “___ the final checks, the engineer approved the design.”', ['Completed', 'To completing', 'Having completed'], 2,
    'The perfect participle marks the checks as completed before the approval.', ['The past participle alone would imply the engineer was completed.', '“To completing” is not a grammatical infinitive or participle phrase.']],
  ['B2', 'grammar', 'sentence-structure', 'Choose the sentence with correct emphasis.', ['Only after the call did we understand the risk.', 'Only after the call we did understand the risk.', 'Only after did the call we understand the risk.'], 0,
    'A negative-style fronted adverbial triggers auxiliary–subject inversion: “did we understand”.', ['The subject and auxiliary remain in ordinary order after a trigger that requires inversion.', 'The inversion is placed inside the prepositional phrase instead of the main clause.']],

  ['B2', 'vocabulary', 'meaning', 'The report presents a “compelling” case for changing the policy. The case is ___.', ['easy to ignore', 'strongly convincing', 'deliberately confusing'], 1,
    'A compelling argument is powerful and persuasive.', ['Something compelling attracts attention rather than inviting dismissal.', 'Confusion is not part of the word’s meaning.']],
  ['B2', 'vocabulary', 'paraphrase', 'The investigators could not “rule out” equipment failure. What does this mean?', ['They established that it caused the failure.', 'They repaired the equipment after the failure.', 'They could not eliminate it as a possible cause.'], 2,
    'To rule something out is to exclude it as a possible explanation.', ['Not excluding a cause is not the same as proving it.', 'The expression concerns judgment, not repair work.']],
  ['B2', 'vocabulary', 'meaning', 'Which verb means “make a harmful effect less severe”?', ['mitigate', 'duplicate', 'anticipate'], 0,
    '“Mitigate” means reduce the seriousness or harmfulness of something.', ['“Duplicate” means copy.', '“Anticipate” means expect or prepare for something.']],
  ['B2', 'vocabulary', 'collocation', 'Complete the sentence: “It is too early to ___ a firm conclusion.”', ['perform', 'draw', 'pull'], 1,
    'The established academic collocation is “draw a conclusion”.', ['“Perform a conclusion” is not idiomatic.', '“Pull a conclusion” is not the standard expression.']],
  ['B2', 'vocabulary', 'meaning', 'The practice is “widespread” across the industry. This means it is ___.', ['carefully hidden', 'limited to one company', 'common in many places'], 2,
    '“Widespread” describes something existing or happening over a large area or among many people.', ['Visibility is separate from extent.', 'Restriction to one company is the opposite of widespread.']],
  ['B2', 'vocabulary', 'collocation', 'Complete the advice: “Please ___ in mind that the figures are provisional.”', ['bear', 'carry', 'hold up'], 0,
    '“Bear in mind” is the fixed expression meaning remember or consider.', ['“Carry in mind” is not the established collocation.', '“Hold up” has different meanings and does not fit this phrase.']],
  ['B2', 'vocabulary', 'register', 'Which sentence is most suitable in a formal evaluation?', ['The project was, frankly, a complete mess from beginning to end.', 'The project achieved some aims but lacked a clear implementation plan.', 'Honestly, the team did a pretty bad job on the whole project.'], 1,
    'This version gives a precise, measured criticism in an appropriately formal register.', ['“Kind of a mess” is vague and conversational.', '“Honestly” and “pretty bad job” are personal and informal.']],
  ['B2', 'vocabulary', 'word-formation', 'Complete the sentence: “The proposal raises questions about the long-term ___ of the service.”', ['sustain', 'sustainable', 'sustainability'], 2,
    'The noun “sustainability” is required after “the long-term”.', ['“Sustain” is a verb.', '“Sustainable” is an adjective and would need to modify a noun.']],
  ['B2', 'vocabulary', 'paraphrase', 'Our plan to share the office “fell through”. What happened?', ['It failed to happen.', 'It became cheaper.', 'It was completed early.'], 0,
    'If a plan falls through, it is not successfully completed or does not happen.', ['The expression says nothing about cost.', 'Early completion is the opposite of failure to happen.']],
  ['B2', 'vocabulary', 'meaning', 'There is a “subtle” difference between the two proposals. The difference is ___.', ['difficult or impossible to explain', 'small and not immediately obvious', 'unacceptable under the relevant law'], 1,
    '“Subtle” describes a fine distinction that may be difficult to notice at first.', ['A subtle difference can still be explained.', 'The word does not make a legal judgment.']],
  ['B2', 'vocabulary', 'paraphrase', 'Several reviewers “took issue with” the final recommendation. They ___.', ['forgot to read it', 'accepted it without question', 'disagreed with or objected to it'], 2,
    'To take issue with something is to disagree with or challenge it.', ['The expression implies an active response, not failure to read.', 'Acceptance without question is the opposite reaction.']],
  ['B2', 'vocabulary', 'meaning', 'A “viable” solution is one that is ___.', ['capable of working successfully', 'popular only in the past', 'difficult to describe'], 0,
    '“Viable” means feasible and capable of succeeding in practice.', ['Past popularity does not establish present feasibility.', 'Ease of description is unrelated to whether a solution can work.']],
] as const;

const upperSeeds: readonly LanguageUseSeed[] = upperSeedRows.map((row) => ({
  level: row[0], skill: row[1], subdomain: row[2], prompt: row[3], options: row[4], correctIndex: row[5],
  rationale: row[6], distractorRationales: row[7],
}));

const seeds: readonly LanguageUseSeed[] = [...lowerSeeds, ...upperSeeds];

const REVISED_ITEM_CONTENT_VERSIONS = new Map<string, string>([
  ['en-a1-vocabulary-07', 'draft-2'],
  ['en-a2-grammar-07', 'draft-2'],
  ['en-a2-grammar-08', 'draft-2'],
  ['en-a2-vocabulary-07', 'draft-2'],
  ['en-a2-vocabulary-08', 'draft-2'],
  ['en-b1-vocabulary-07', 'draft-2'],
  ['en-b1-vocabulary-12', 'draft-2'],
  ['en-b2-grammar-04', 'draft-2'],
  ['en-b2-grammar-08', 'draft-2'],
  ['en-b2-vocabulary-02', 'draft-2'],
  ['en-b2-vocabulary-07', 'draft-2'],
  ['en-b2-vocabulary-10', 'draft-2'],
]);

function itemId(seed: LanguageUseSeed, ordinal: number): string {
  return `en-${seed.level.toLowerCase()}-${seed.skill}-${String(ordinal).padStart(2, '0')}`;
}

export const ENGLISH_DIAGNOSTIC_LANGUAGE_USE_CANDIDATES: readonly DiagnosticBankRecord[] = seeds.map((seed, index) => {
  const sameCellOrdinal = seeds.slice(0, index + 1)
    .filter((candidate) => candidate.level === seed.level && candidate.skill === seed.skill).length;
  const id = itemId(seed, sameCellOrdinal);
  const contentVersion = REVISED_ITEM_CONTENT_VERSIONS.get(id) ?? 'draft-1';
  const optionIds = seed.options.map((_, optionIndex) => `${id}-o${optionIndex + 1}`);
  const distractorIndexes = [0, 1, 2].filter((optionIndex) => optionIndex !== seed.correctIndex);
  return {
    publicItem: {
      id,
      contentVersion,
      language: 'en',
      skill: seed.skill,
      subdomain: seed.subdomain,
      levelCandidate: seed.level,
      prompt: seed.prompt,
      stimulus: { kind: 'none' },
      response: { kind: 'single-choice', optionIds },
      displayOptions: seed.options.map((text, optionIndex) => ({ id: optionIds[optionIndex], text })),
    },
    status: 'reserved',
    exposure: 'reserved',
    review: { status: 'draft' },
    scoring: { kind: 'single-choice', optionId: optionIds[seed.correctIndex] },
    rationale: {
      key: seed.rationale,
      distractors: Object.fromEntries(distractorIndexes.map((optionIndex, rationaleIndex) => [
        optionIds[optionIndex], seed.distractorRationales[rationaleIndex],
      ])),
    },
    source: {
      kind: 'welearn-original',
      reference: contentVersion === 'draft-1'
        ? ENGLISH_DIAGNOSTIC_LANGUAGE_USE_CANDIDATE_VERSION
        : ENGLISH_DIAGNOSTIC_LANGUAGE_USE_REVISED_VERSION,
    },
    levelRange: [seed.level, seed.level],
    warnings: ['PENDING_INDEPENDENT_LINGUISTIC_REVIEW', 'PENDING_PILOT_CALIBRATION'],
  };
});
