'use client';

import { useMemo, useState } from 'react';

type Item = { level: 1 | 2 | 3; prompt: string; options: string[]; correct: number; slot: 0 | 1 | 2 | 3; explanation: string };
const ITEMS: Item[] = [
  { level: 1, prompt: 'A park becomes a housing estate in the north-west. Which sentence reports the visible change?', options: ['The park in the north-west was replaced by a housing estate.', 'The park improved the quality of life in the town.', 'The housing estate was more popular than the park.', 'The park was moved to the south-east.'], correct: 0, slot: 1, explanation: 'The accurate sentence names the original feature, the new feature and its location without adding an unsupported reason or evaluation.' },
  { level: 1, prompt: 'A small road is widened into a dual carriageway. Choose the precise map language.', options: ['The small road was widened into a dual carriageway.', 'The road grew because traffic increased.', 'The dual carriageway was smaller than the road.', 'The road disappeared without replacement.'], correct: 0, slot: 3, explanation: 'Widened into describes the visible transformation. A map does not prove why the change happened.' },
  { level: 1, prompt: 'A former car park is replaced by a shopping centre in the south-east. Which phrase names its location precisely?', options: ['in the south-eastern area', 'during the next stage', 'at a higher proportion', 'between 2000 and 2020 people'], correct: 0, slot: 0, explanation: 'Maps require spatial language. In the south-eastern area identifies where the visible change takes place.' },
  { level: 1, prompt: 'A market is replaced by a food court. Which verb phrase describes this change without adding a reason?', options: ['was redeveloped as a food court', 'became popular because visitors needed food', 'rose steadily into a food court', 'was similar to a food court in 2020'], correct: 0, slot: 2, explanation: 'Was redeveloped as reports only the visible transformation. The other choices add unsupported causes or use chart language.' },
  { level: 2, prompt: 'Which overview best summarises a map showing new housing, a school and wider roads?', options: ['Overall, the area became more developed, with former open or industrial land replaced by housing and services.', 'Overall, the school is next to the main road.', 'Overall, the population doubled during the period.', 'Overall, the redevelopment was successful.'], correct: 0, slot: 2, explanation: 'A strong map overview captures the dominant land-use change and avoids unsupported figures, causes and judgements.' },
  { level: 2, prompt: 'Which organisation groups changes most clearly for a body paragraph?', options: ['Describe every label in clockwise order, even if nothing changed.', 'Group changes by area, such as the northern half, southern half and transport network.', 'Write one paragraph about opinions and one about predictions.', 'List only the largest building.'], correct: 1, slot: 0, explanation: 'Grouping by area helps the reader follow spatial relationships and prevents a disconnected list.' },
  { level: 2, prompt: 'A campus map shows a library and student flats in the north, plus a cycle path and sports centre in the south. Which Body 1 focus is logical?', options: ['The northern redevelopment: the lecture hall and garden were replaced by a library and student flats.', 'Every building in the south should be listed before the north.', 'How students feel about the new facilities.', 'Predictions about the next thirty years.'], correct: 0, slot: 3, explanation: 'Grouping the northern changes in one detail paragraph gives the reader a clear spatial structure and leaves the southern changes for Body 2.' },
  { level: 2, prompt: 'Which sentence reports a retained feature accurately?', options: ['The main entrance remained in the same position.', 'The main entrance was replaced by an entrance.', 'The main entrance increased sharply.', 'The main entrance was more successful than before.'], correct: 0, slot: 1, explanation: 'Remained in the same position is appropriate when a visible feature does not change. The other options misuse map or chart language.' },
  { level: 3, prompt: 'A fishing harbour becomes a marina, northern fields become a resort and a narrow road becomes a main road. Select the best overview.', options: ['Overall, the village underwent substantial development, including changes to the harbour, northern land use and main road.', 'Overall, the marina was built because tourism increased.', 'Overall, the fields covered 40% of the village.', 'Overall, the village was better in 2025.'], correct: 0, slot: 0, explanation: 'The answer synthesises the main spatial transformations while remaining faithful to the visual evidence.' },
  { level: 3, prompt: 'Which sentence combines location, change and comparison accurately?', options: ['The former car park in the south-west was replaced by a cycle path, while the sports field became a sports centre.', 'The cycle path caused students to exercise more.', 'The sports centre was north of the old sports field in every map.', 'The car park was expanded into a larger car park.'], correct: 0, slot: 2, explanation: 'The sentence links two supported transformations and uses while to create a controlled comparison.' },
  { level: 3, prompt: 'Which sentence avoids turning a map into a list?', options: ['In the north, recreational and industrial land was replaced by housing and a school, whereas the southern area gained a shopping centre.', 'There was a park. There was a factory. There was a road. There was a car park.', 'The town changed because the government wanted it to grow.', 'The map has four corners, and each one has a different building.'], correct: 0, slot: 1, explanation: 'The best sentence groups related changes by area and function. It reports the map rather than listing labels or inventing causes.' },
  { level: 3, prompt: 'A map has a before and after plan but no dates. Which opening is accurate?', options: ['The maps compare the layout of the shopping centre before and after redevelopment.', 'The maps show the percentage of visitors over a twenty-year period.', 'The maps prove that the redevelopment was financially successful.', 'The maps explain why shoppers preferred the new centre.'], correct: 0, slot: 3, explanation: 'When dates are not shown, before and after redevelopment is accurate. A map cannot demonstrate percentages, success or visitor motives unless those details are shown.' },
];

function arrange(item: Item) { const correctOption = item.options[item.correct]; const distractors = item.options.filter((_, index) => index !== item.correct); const options = [...distractors]; options.splice(item.slot, 0, correctOption); return { options, correct: item.slot }; }

export default function MapPracticeEngine() {
  const [level, setLevel] = useState<1 | 2 | 3>(1); const [index, setIndex] = useState(0); const [selected, setSelected] = useState<number | null>(null); const [checked, setChecked] = useState(false);
  const items = ITEMS.filter((item) => item.level === level); const current = items[index % items.length]; const displayed = useMemo(() => arrange(current), [current]);
  function chooseLevel(value: 1 | 2 | 3) { setLevel(value); setIndex(0); setSelected(null); setChecked(false); }
  return <section aria-labelledby="map-progressive-engine" style={{ marginTop: '2.5rem' }}>
    <p className="eyebrow"><span className="ink-line" />WeLearn progressive engine</p><h2 id="map-progressive-engine" style={{ margin: '0 0 0.4rem', fontSize: '1.45rem' }}>Practise map writing by level</h2><p style={{ margin: '0 0 1.1rem', color: 'var(--muted)', lineHeight: 1.65 }}>Identify a visible change first, then organise spatial evidence and build a cautious map overview.</p>
    <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap', marginBottom: '1rem' }}>{([1, 2, 3] as const).map((item) => <button key={item} type="button" className="btn btn-sm" aria-pressed={level === item} onClick={() => chooseLevel(item)} style={{ flex: '1 1 170px', textAlign: 'left', opacity: level === item ? 1 : 0.68 }}><strong>Level {item}</strong><br /><span style={{ fontSize: '0.72rem' }}>{item === 1 ? 'Location and change' : item === 2 ? 'Grouping and overview' : 'Precise map sentences'}</span></button>)}</div>
    <div className="wl-card" style={{ padding: '1.15rem', borderTop: '4px solid #0f3d8c' }}><div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.85rem', color: '#0f3d8c', fontFamily: 'var(--mono)', fontSize: '0.72rem', fontWeight: 900 }}><span>Exercise {index + 1} of {items.length}</span><span>Level {level}</span></div><p style={{ margin: 0, padding: '0.8rem 0.9rem', borderLeft: '3px solid #0f3d8c', background: 'rgba(15,61,140,0.05)', lineHeight: 1.55, fontStyle: 'italic' }}>&ldquo;{current.prompt}&rdquo;</p><div style={{ display: 'grid', gap: '0.55rem', marginTop: '0.9rem' }}>{displayed.options.map((option, optionIndex) => <button key={option} type="button" onClick={() => !checked && setSelected(optionIndex)} aria-pressed={selected === optionIndex} style={{ textAlign: 'left', padding: '0.8rem 0.9rem', borderRadius: 8, border: `1.5px solid ${checked && optionIndex === displayed.correct ? '#059669' : checked && selected === optionIndex ? '#dc2626' : selected === optionIndex ? '#0f3d8c' : 'var(--line-soft)'}`, background: checked && optionIndex === displayed.correct ? 'rgba(5,150,105,0.08)' : selected === optionIndex ? 'rgba(15,61,140,0.06)' : 'var(--bg)', color: 'var(--ink)', cursor: checked ? 'default' : 'pointer', lineHeight: 1.55 }}>{String.fromCharCode(65 + optionIndex)}. {option}</button>)}</div><div style={{ display: 'flex', gap: '0.6rem', marginTop: '1rem', flexWrap: 'wrap' }}><button type="button" className="btn btn-sm" onClick={() => setChecked(true)} disabled={selected === null || checked}>{checked ? (selected === displayed.correct ? 'Correct' : 'Review the explanation') : 'Check answer'}</button>{checked && <button type="button" className="btn btn-sm" onClick={() => { setIndex((value) => (value + 1) % items.length); setSelected(null); setChecked(false); }}>Next exercise →</button>}</div>{checked && <div role="status" style={{ marginTop: '0.85rem', padding: '0.8rem 0.9rem', borderRadius: 8, background: selected === displayed.correct ? 'rgba(5,150,105,0.08)' : 'rgba(217,119,6,0.08)' }}><strong>{selected === displayed.correct ? 'Good work.' : 'Review the evidence.'}</strong><p style={{ margin: '0.25rem 0 0', color: 'var(--ink-2)', lineHeight: 1.55 }}>{current.explanation}</p></div>}</div>
  </section>;
}
