'use client';

import { Fragment, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, CheckSquare2, Layers3 } from 'lucide-react';
import Task2OfficialReviewBlock from '../Task2OfficialReviewBlock';
import type { EssayTypeId } from '../introduccion/introduction-data';
import ColoredBodyParagraph from '../body-1/ColoredBodyParagraph';
import { CONCLUSION_LESSONS } from './conclusion-data';
import ConclusionWorkshop from './ConclusionWorkshop';
import ConclusionPracticeEngine from './ConclusionPracticeEngine';
import styles from '../introduccion/page.module.css';

export default function ConclusionTask2Client() {
  const [activeType, setActiveType] = useState<EssayTypeId>('opinion');
  const [activeExample, setActiveExample] = useState(1);
  const lesson = CONCLUSION_LESSONS.find((item) => item.id === activeType) ?? CONCLUSION_LESSONS[0];
  const worked = lesson.examples[0]; const example = lesson.examples[activeExample];
  return <div lang="en" className={styles.page}><div className={styles.shell}>
    <nav className={styles.breadcrumb} aria-label="Breadcrumb"><Link href="/practica/ielts/academic/writing/task2"><ArrowLeft size={15} /> Task 2</Link><span>/</span><span>Conclusion</span></nav>
    <header className={styles.hero}><p className={styles.eyebrow}>Task 2 · Build the essay · Step 5</p><h1>Write an IELTS Task 2 conclusion that completes the answer</h1><p className={styles.heroLead}>Restate the same position, synthesise only developed reasoning and adapt the closing blocks to the exact question family.</p><div className={styles.factGrid}><div className={styles.fact}><strong>0 new ideas</strong><span>the conclusion closes existing reasoning</span></div><div className={styles.fact}><strong>2–3 blocks</strong><span>the architecture changes with the prompt</span></div><div className={styles.fact}><strong>30–50</strong><span>WeLearn study target, not an official limit</span></div><div className={styles.fact}><strong>5 families</strong><span>each requires a different final answer</span></div></div><div className={styles.heroActions}><a href="#guided-workshop">Practice with the boxes</a><a href="#practice-engine">Open the level engine</a></div></header>
    <section className={styles.section}><div className={styles.sectionHeading}><p className={styles.kicker}>Official format and WeLearn strategy</p><h2>IELTS assesses the complete response, not a memorised conclusion formula</h2></div><Task2OfficialReviewBlock focus="Complete the response by preserving its position and synthesising its developed reasoning." officialFormat="IELTS Academic Writing Task 2 requires a connected response of at least 250 words. It does not prescribe a conclusion length, opening phrase or fixed number of sentences." welearnStrategy="WeLearn uses a flexible 30–50-word study target and question-sensitive closing blocks. These are planning tools, not official paragraph rules." answerCheck="Compare the conclusion with the prompt, thesis and body paragraphs. It must preserve the answer and contain no undeveloped argument, example or prediction." /></section>
    <section className={styles.section}><div className={styles.sectionHeading}><p className={styles.kicker}>Sentence Lego · Conclusion</p><h2>The final blocks change when the instruction changes</h2><p>A discussion closes two views and a judgement; direct questions close two answers. Neither can use the same formula as an opinion essay.</p></div><div className={styles.legoRow}>{lesson.architecture.map((block, index) => <div key={block.label} className={`${styles.legoBlock} ${styles[block.tone]}`} style={{ animationDelay: `${index * 90}ms` }}><strong>{block.label}</strong><p>{block.purpose}</p></div>)}</div><div className={styles.bodyFormula}>{lesson.architecture.map((block, index) => <Fragment key={block.label}><span>{block.label}</span>{index < lesson.architecture.length - 1 && <ArrowRight size={18} />}</Fragment>)}</div></section>
    <section className={styles.section}><div className={styles.sectionHeading}><p className={styles.kicker}>Five question families</p><h2>Decide what the conclusion must preserve</h2></div><div className={styles.typeTabs} role="tablist">{CONCLUSION_LESSONS.map((item) => <button key={item.id} type="button" role="tab" aria-selected={item.id === activeType} className={`${styles.typeTab} ${item.id === activeType ? styles.typeTabActive : ''}`} onClick={() => { setActiveType(item.id); setActiveExample(1); }}>{item.shortLabel}</button>)}</div><article className={styles.typePanel}><div className={styles.typeIntro}><div><h3>{lesson.label}</h3><p className={styles.signal}><strong>Instruction signal:</strong> {lesson.signal}</p><div className={styles.strategyList}><p><strong>Conclusion function:</strong> {lesson.function}</p><p><strong>Planning question:</strong> {lesson.planningQuestion}</p></div></div><p className={styles.trap}><strong>Common trap</strong><br />{lesson.trap}</p></div></article></section>
    <section id="guided-workshop" className={styles.section}><div className={styles.sectionHeading}><p className={styles.kicker}>Watch one · then do four</p><h2>Study one complete conclusion, then build four</h2><p>First see the closing functions in context. Then make the same decisions without being given the answer.</p></div><article className={`${styles.examplePanel} ${styles.workedExample}`}><div className={styles.workedBadge}>Worked example · {worked.title}</div><div className={styles.promptCard}><span>IELTS-style prompt</span><p>{worked.prompt}</p></div><div className={styles.modelBlockGrid}>{worked.blocks.map((block) => <article key={block.label} className={styles[block.tone]}><strong>{block.label}</strong><p>{block.text}</p><small>{block.purpose}</small></article>)}</div><div className={styles.completeParagraph}><strong>Read the blocks as one conclusion</strong><ColoredBodyParagraph blocks={worked.blocks} /></div><p className={styles.mistakeNote}><strong>Precision check:</strong> {worked.commonMistake}</p></article><div className={styles.tryDivider}><span>Now you try</span><p>The model remains hidden until you preserve the answer and write every required block.</p></div><div className={styles.exampleTabs}>{lesson.examples.slice(1).map((item, offset) => { const index = offset + 1; return <button key={item.title} type="button" className={`${styles.exampleTab} ${activeExample === index ? styles.exampleTabActive : ''}`} onClick={() => setActiveExample(index)}>{String(index + 1).padStart(2, '0')} · {item.title}</button>; })}</div><article className={styles.examplePanel}><div className={styles.promptCard}><span>Your IELTS-style prompt</span><p>{example.prompt}</p></div><ConclusionWorkshop key={`${activeType}-${activeExample}`} example={example} seed={activeExample + CONCLUSION_LESSONS.findIndex((item) => item.id === activeType)} /></article></section>
    <ConclusionPracticeEngine essayType={activeType} />
    <section className={styles.section}><div className={styles.sectionHeading}><p className={styles.kicker}>Frequently asked questions</p><h2>Close the answer without making it mechanical</h2></div><div className={styles.faqGrid}><article><h3>How long should the conclusion be?</h3><p>IELTS sets no paragraph limit. WeLearn uses about 30–50 words as a flexible study target inside a complete response of at least 250 words.</p></article><article><h3>Must it begin with “In conclusion”?</h3><p>No. A clear closing signal can help, but accurate synthesis and a consistent answer matter more than one memorised phrase.</p></article><article><h3>Can I add a recommendation?</h3><p>Only when it follows directly from reasoning already developed. Do not introduce a new policy, example or prediction in the conclusion.</p></article><article><h3>Should I repeat my thesis?</h3><p>Restate the same answer with fresh language. Copying the introduction wastes words; changing the position creates inconsistency.</p></article></div></section>
    <nav className={styles.nextLinks}><Link href="/practica/ielts/academic/writing/task2/body-2"><Layers3 size={18} /> Build Body 2</Link><Link href="/practica/ielts/academic/writing/task2/revision-final">Run Final Review <CheckSquare2 size={18} /></Link><Link href="/practica/ielts/academic/writing/task2/tarea-completa">Complete Essay Practice <ArrowRight size={16} /></Link></nav>
  </div></div>;
}
