import 'server-only';

// Editorial archive for the Academic Passage blocks superseded in W6. The
// exact passages and answer identities stay private so the rewrite remains
// reversible without exposing keys or returning old claims to learners.
export const TOEFL_READING_SETS_11_TO_15_LEGACY_SOURCES = [
  {
    id: 'source:t11-r-ap-antibiotic-resistance-v1',
    passage: `Antibiotics are among the most important discoveries in the history of medicine. Before their widespread use, a simple infection from a cut or a common illness such as pneumonia could easily be fatal. The introduction of penicillin in the 1940s transformed medicine, turning once-deadly infections into treatable conditions and making complex surgeries far safer. Yet the very success of antibiotics has created a serious and growing problem: antibiotic resistance.\n\nAntibiotics work by killing bacteria or stopping them from reproducing. However, bacteria reproduce rapidly, and through random genetic mutation, some individuals may happen to survive exposure to a drug. These survivors pass on their resistance to the next generation. Over time, as we use more and more antibiotics, we unintentionally select for bacteria that the drugs can no longer kill. This is evolution by natural selection, playing out in a matter of days rather than millennia.\n\nSeveral human behaviors accelerate this process. Taking antibiotics when they are not needed—for instance, for viral infections like the common cold, which antibiotics cannot treat—exposes bacteria to drugs unnecessarily. Failing to complete a prescribed course can leave behind the hardier bacteria. The heavy use of antibiotics in agriculture, where they are often given to healthy livestock to promote growth, adds further pressure. As a result, "superbugs" resistant to multiple antibiotics have emerged, and infections that were once easily cured are becoming difficult or impossible to treat.\n\nScientists are responding on several fronts: searching for new antibiotics, developing rapid tests so doctors prescribe them only when necessary, and promoting more careful use worldwide. But developing new antibiotics is slow and expensive, and bacteria continue to evolve. Many experts warn that without coordinated global action, we could enter a "post-antibiotic era" in which common infections once again become life-threatening—a sobering reminder that a medical triumph, if used carelessly, can be undermined by the very organisms it was designed to defeat.`,
    items: [{ id: 't11-r-ap1', answer: 2 }, { id: 't11-r-ap2', answer: 3 }, { id: 't11-r-ap3', answer: 0 }, { id: 't11-r-ap4', answer: 1 }, { id: 't11-r-ap5', answer: 2 }, { id: 't11-r-ap6', answers: ['A', 'C'] }],
  },
  {
    id: 'source:t12-r-ap-great-barrier-reef-v1',
    passage: `The Great Barrier Reef, stretching more than 2,300 kilometers along the northeast coast of Australia, is the largest living structure on Earth—so large it can be seen from space. Yet it is built by animals barely a few millimeters across: coral polyps. Understanding how such a colossal structure arises from such tiny builders reveals a great deal about how complex natural systems can emerge from simple, repeated actions.\n\nEach coral polyp secretes a hard skeleton of calcium carbonate. When a polyp dies, its skeleton remains, and new polyps grow on top. Over thousands of years, generation upon generation of these skeletons accumulate into the massive reef structures we see today. In this way, the reef is less a single organism than a vast city, continuously built up by countless small inhabitants, most of whom are long dead.\n\nThe reef is far more than rock, however. It is one of the most biologically diverse ecosystems on the planet, home to thousands of species of fish, mollusks, and other marine life. This diversity is not accidental. The complex, three-dimensional structure of the reef creates an enormous variety of habitats—crevices, overhangs, and channels—each suited to different organisms. Ecologists describe corals as "ecosystem engineers" because, by building physical structure, they create the conditions that allow many other species to thrive.\n\nBut this achievement is fragile. Because reef-building corals depend on the delicate partnership with their algae, they are highly sensitive to changes in water temperature and chemistry. In recent decades, rising sea temperatures have caused repeated mass bleaching events, and ocean acidification threatens the corals' ability to build their skeletons. The paradox is striking: a structure that took millions of years and countless generations to build could be severely damaged within a human lifetime. Protecting it, scientists argue, requires addressing the global causes of ocean warming, not just local threats.`,
    items: [{ id: 't12-r-ap1', answer: 1 }, { id: 't12-r-ap2', answer: 2 }, { id: 't12-r-ap3', answer: 3 }, { id: 't12-r-ap4', answer: 0 }, { id: 't12-r-ap5', answer: 1 }, { id: 't12-r-ap6', answers: ['A', 'C'] }],
  },
  {
    id: 'source:t13-r-ap-gps-v1',
    passage: `For thousands of years, humans navigated using the stars, the sun, and familiar landmarks. But over the past few decades, a technology has quietly transformed how we find our way: the Global Positioning System, or GPS. Today, GPS guides everything from smartphones and cars to ships, aircraft, and even farm equipment. Yet few people understand the elegant science that makes it work.\n\nGPS relies on a network of satellites orbiting the Earth, each continuously broadcasting a signal that includes the exact time the signal was sent and the satellite's position. A GPS receiver—in your phone, for example—listens for these signals. Because radio waves travel at a known speed, the receiver can calculate how far away each satellite is by measuring how long the signal took to arrive. With the distance to one satellite, you could be anywhere on a sphere around it. But with signals from four or more satellites, the receiver can pinpoint its exact location on the Earth's surface, a process called trilateration.\n\nWhat is remarkable is the precision required. The satellites carry extremely accurate atomic clocks, because even a tiny timing error—a millionth of a second—would translate into a position error of hundreds of meters. In fact, the system is so sensitive to time that it must account for effects predicted by Einstein's theory of relativity: clocks on the fast-moving satellites, high above the Earth, tick at a slightly different rate than clocks on the ground. If engineers ignored this, GPS would quickly become useless.\n\nGPS was originally developed for military purposes, but it was later made available for civilian use, unleashing a wave of innovation no one fully anticipated. It has reshaped transportation, agriculture, emergency response, and countless everyday activities. It is a striking example of how fundamental physics—precise timekeeping and relativity—can quietly underpin a technology billions of people now depend on without a second thought.`,
    items: [{ id: 't13-r-ap1', answer: 0 }, { id: 't13-r-ap2', answer: 1 }, { id: 't13-r-ap3', answer: 2 }, { id: 't13-r-ap4', answer: 3 }, { id: 't13-r-ap5', answer: 0 }, { id: 't13-r-ap6', answers: ['A', 'C'] }],
  },
  {
    id: 'source:t14-r-ap-bees-pollination-v1',
    passage: `Bees are famous for their honey, but their most important contribution to human life is something less obvious: pollination. As bees travel from flower to flower gathering nectar, they carry pollen with them, fertilizing plants so they can produce seeds and fruit. A remarkable proportion of the crops humans depend on—apples, almonds, blueberries, and many more—rely on insect pollination, and bees are the most important pollinators of all. Without them, both wild plants and agriculture would suffer enormously.\n\nWhat makes bees such effective pollinators is not merely their numbers but their behavior. A single honeybee tends to visit flowers of just one species during a foraging trip, a tendency known as flower constancy. This is highly efficient for the plant, because pollen from an apple flower is far more likely to be carried to another apple flower rather than wasted on an unrelated species. In effect, the bee and the flowering plant have evolved a partnership from which both benefit: the bee gets food, and the plant gets reproduction.\n\nIn recent years, however, beekeepers around the world have reported alarming declines in bee populations. A phenomenon called colony collapse disorder, in which the worker bees of a hive suddenly disappear, has drawn particular attention. Scientists have not identified a single cause; rather, the decline appears to result from a combination of pressures: certain pesticides, parasites such as the varroa mite, loss of wildflower habitat, and disease. These factors may weaken bees individually and interact in ways that overwhelm a colony.\n\nThe implications are serious. If pollinators continue to decline, the cost of pollinating crops could rise sharply, and some foods could become scarcer and more expensive. Efforts to help include reducing harmful pesticide use, planting wildflowers to provide forage, and supporting research into bee health. Ultimately, the fate of bees is a reminder of how deeply human well-being is entangled with the health of the natural world—often through creatures we rarely stop to notice.`,
    items: [{ id: 't14-r-ap1', answer: 3 }, { id: 't14-r-ap2', answer: 0 }, { id: 't14-r-ap3', answer: 1 }, { id: 't14-r-ap4', answer: 2 }, { id: 't14-r-ap5', answer: 3 }, { id: 't14-r-ap6', answers: ['A', 'C'] }],
  },
  {
    id: 'source:t15-r-ap-child-language-v1',
    passage: `Human language is one of the most distinctive features of our species, and among its many puzzles, one of the most fascinating is how children acquire it. By the age of five, most children can understand and produce thousands of words and construct grammatically complex sentences—all without formal instruction. How they accomplish this so quickly and reliably has been debated for decades.\n\nOne influential view, associated with the linguist Noam Chomsky, holds that humans are born with an innate capacity for language. According to this view, the human brain contains a kind of built-in framework—sometimes called a "language faculty"—that equips children to detect the underlying rules of any human language they are exposed to. Supporters point out that children produce grammatical patterns they could not simply have copied, and that they make certain systematic errors, such as saying "goed" instead of "went," which suggests they are applying internal rules rather than imitating.\n\nA contrasting view emphasizes learning and social interaction. Researchers in this tradition argue that children acquire language primarily by detecting statistical patterns in the speech they hear and by using powerful general learning abilities, guided by their desire to communicate with the people around them. On this account, the sheer amount of language input a child receives, and the back-and-forth of everyday conversation, do much of the work.\n\nMost researchers today accept that the truth involves both nature and nurture. Children clearly bring remarkable cognitive abilities to the task, and human brains do seem specially prepared for language in ways that other animals' brains are not. But the specific language a child learns, and the pace at which they learn it, depend heavily on the input and interaction they receive. A child raised in a rich language environment learns faster than one who hears little speech. Language acquisition, then, is neither purely instinctive nor purely learned; it emerges from the interaction between a prepared mind and a language-rich world.`,
    items: [{ id: 't15-r-ap1', answer: 2 }, { id: 't15-r-ap2', answer: 3 }, { id: 't15-r-ap3', answer: 0 }, { id: 't15-r-ap4', answer: 1 }, { id: 't15-r-ap5', answer: 2 }, { id: 't15-r-ap6', answers: ['A', 'C'] }],
  },
] as const;
