import 'server-only';

// Editorial archive for the Academic Passage blocks superseded in W7. Exact
// passages and answer identities stay private so the rewrite remains reversible.
export const TOEFL_READING_SETS_16_TO_20_LEGACY_SOURCES = [
  {
    id: 'source:t16-r-ap-brain-myth-v1',
    passage: `The idea that we use only ten percent of our brains is one of the most persistent myths about human biology. It appears in advertisements, self-help books, and films, often accompanied by the tantalizing suggestion that if we could just "unlock" the rest, we might gain extraordinary powers. It is a compelling story. It is also false.\n\nModern neuroscience gives us many tools to observe the brain in action. Brain-imaging techniques, such as functional MRI, allow researchers to watch which areas become active during different tasks. What these studies consistently show is that, over the course of a day, virtually every region of the brain is used. Even during sleep, many areas remain active. There is no large, silent portion waiting to be switched on. Different tasks recruit different regions, but there is no evidence of a vast unused reserve.\n\nThere are also strong evolutionary and biological arguments against the myth. The brain is extraordinarily expensive to run: although it makes up only about two percent of body weight, it consumes roughly twenty percent of the body's energy. It would make no evolutionary sense for us to carry around such a costly organ if ninety percent of it did nothing. Natural selection tends to eliminate wasteful features, not preserve them. Furthermore, damage to almost any part of the brain—through stroke or injury—produces some noticeable effect, which would be strange if most of the brain were inactive.\n\nWhy, then, does the myth survive? Part of the appeal is optimistic: the idea that we have hidden potential is more inspiring than the reality that we are already using our full capacity. The myth may also stem from a misunderstanding of early neuroscience, when scientists could not yet identify the function of every brain region and may have described large portions as having "unknown" functions. "Unknown" was mistranslated, over time, into "unused." The truth is less magical but more remarkable: the brain we already have, fully in use, is one of the most complex and capable structures known to exist.`,
    items: [{ id: 't16-r-ap1', answer: 1 }, { id: 't16-r-ap2', answer: 2 }, { id: 't16-r-ap3', answer: 3 }, { id: 't16-r-ap4', answer: 0 }, { id: 't16-r-ap5', answer: 1 }, { id: 't16-r-ap6', answers: ['A', 'C'] }],
  },
  {
    id: 'source:t17-r-ap-flow-v1',
    passage: `The concept of "flow" describes a mental state in which a person is fully immersed in an activity, feeling energized, focused, and deeply engaged. First studied systematically by the psychologist Mihaly Csikszentmihalyi in the 1970s, flow has become one of the most influential ideas in the psychology of motivation and well-being. People often describe it informally as being "in the zone."\n\nWhat distinguishes flow from ordinary concentration is its intensity and quality. In a flow state, people report losing track of time, forgetting about themselves and their worries, and performing at their best almost effortlessly. Athletes, musicians, surgeons, and chess players all describe strikingly similar experiences, despite the very different nature of their activities. This consistency across domains suggests that flow reflects a general feature of how the human mind works when deeply engaged.\n\nCsikszentmihalyi identified the conditions that tend to produce flow. Perhaps the most important is a balance between challenge and skill. If a task is too easy relative to a person's ability, they become bored; if it is too difficult, they become anxious. Flow occurs in the narrow band where the challenge stretches a person's skills without overwhelming them. Other conditions include clear goals and immediate feedback, which allow a person to adjust their actions moment by moment without stopping to second-guess themselves.\n\nThe practical implications are significant. Research suggests that people who experience flow more often report greater life satisfaction, and that flow is associated with better learning and performance. This has led educators to design lessons that keep challenge and skill in balance, and workplaces to structure tasks so that employees can enter flow more readily. Yet flow cannot simply be commanded into existence; it arises indirectly, as a by-product of the right conditions. The lesson many draw from the research is not to chase happiness directly, but to seek out activities that are challenging, meaningful, and matched to one's abilities—and to let the deep satisfaction of flow follow naturally.`,
    items: [{ id: 't17-r-ap1', answer: 0 }, { id: 't17-r-ap2', answer: 1 }, { id: 't17-r-ap3', answer: 2 }, { id: 't17-r-ap4', answer: 3 }, { id: 't17-r-ap5', answer: 0 }, { id: 't17-r-ap6', answers: ['A', 'C'] }],
  },
  {
    id: 'source:t18-r-ap-vaccines-v1',
    passage: `Vaccines are one of the greatest achievements in the history of public health, responsible for saving millions of lives and eliminating or controlling diseases that once killed or disabled vast numbers of people. To understand why they are so powerful, it helps to understand the elegant biological principle on which they rely: training the immune system without causing the disease itself.\n\nThe human immune system has a remarkable ability to remember. When it encounters a harmful microbe—a virus or bacterium—for the first time, it mounts a defense, and afterward it retains a "memory" of that microbe. If the same microbe appears again, the immune system recognizes it and responds far more quickly and powerfully, often stopping the infection before it causes illness. A vaccine takes advantage of this memory. By exposing the body to a harmless version or piece of a microbe—too weak or incomplete to cause disease—a vaccine teaches the immune system to recognize the real threat in advance.\n\nBeyond protecting the individual who receives it, vaccination offers a benefit to the whole community, known as herd immunity. When a large enough proportion of a population is immune to a disease, the microbe can no longer spread easily from person to person, because it keeps encountering people who cannot pass it on. This indirectly protects those who cannot be vaccinated, such as newborn babies or people with certain medical conditions. Herd immunity is why some diseases can be pushed to very low levels, or even eliminated, when vaccination rates are high.\n\nThe dramatic success of vaccines has, paradoxically, contributed to complacency in some places. Because vaccines have made once-common diseases rare, many people have never witnessed how devastating those diseases can be, and some underestimate the importance of vaccination. When vaccination rates fall, however, diseases that were nearly eliminated can return. The history of public health offers a clear lesson: the protection vaccines provide is powerful but not permanent at the population level. It must be maintained, generation after generation, through continued vaccination.`,
    items: [{ id: 't18-r-ap1', answer: 3 }, { id: 't18-r-ap2', answer: 0 }, { id: 't18-r-ap3', answer: 1 }, { id: 't18-r-ap4', answer: 2 }, { id: 't18-r-ap5', answer: 3 }, { id: 't18-r-ap6', answers: ['A', 'C'] }],
  },
  {
    id: 'source:t19-r-ap-dreams-v1',
    passage: `Why do we dream? Despite being one of the most universal human experiences, dreaming remains among the least understood. Everyone dreams, whether or not they remember it, and dreams have fascinated people for thousands of years. Modern science has offered several theories, but no single explanation has won universal agreement—which itself tells us something about how difficult the question is.\n\nOne influential idea comes from the field of neuroscience and is sometimes called the "activation-synthesis" theory. According to this view, during a stage of sleep called REM sleep, the brain becomes highly active, generating bursts of electrical signals. The higher, thinking parts of the brain then try to make sense of this random internal activity by weaving it into a story. On this account, dreams are, in part, the brain's attempt to impose meaning on essentially random signals—which might explain why dreams are often so strange and disjointed.\n\nA very different family of theories emphasizes function—the idea that dreaming does something useful. Some researchers propose that dreams help process emotions, allowing us to work through fears and difficult experiences in a safe, imaginary space. Others suggest that dreaming plays a role in memory, helping the brain sort through and consolidate the day's experiences, strengthening important memories and discarding trivial ones. A related idea is that dreams act as a kind of rehearsal, letting us practice responses to threats or challenges without real-world consequences.\n\nIt is quite possible that more than one of these theories is partly correct, and that dreaming serves several functions at once. What is clear is that sleep and dreaming are far from passive states; the sleeping brain is doing significant work. And the very difficulty of studying dreams—the fact that they are private, fleeting, and hard to recall accurately—reminds us that even the most ordinary parts of human experience can contain deep and unresolved scientific mysteries.`,
    items: [{ id: 't19-r-ap1', answer: 2 }, { id: 't19-r-ap2', answer: 3 }, { id: 't19-r-ap3', answer: 0 }, { id: 't19-r-ap4', answer: 1 }, { id: 't19-r-ap5', answer: 2 }, { id: 't19-r-ap6', answers: ['A', 'C'] }],
  },
  {
    id: 'source:t20-r-ap-dark-matter-energy-v1',
    passage: `One of the most surprising discoveries in modern astronomy is that the ordinary matter we can see—stars, planets, gas, and everything made of atoms—accounts for only a small fraction of the universe. The rest appears to be made of two mysterious components that scientists call dark matter and dark energy. Despite their similar names, they are quite different, and together they represent one of the great unsolved problems in physics.\n\nDark matter was proposed to explain a puzzle about how galaxies behave. When astronomers measured the speed at which stars orbit within galaxies, they found that the outer stars were moving far too fast. Based on the visible matter alone, these fast-moving stars should have flown off into space; the gravity of the visible stars and gas was simply not strong enough to hold them. The leading explanation is that galaxies contain a large amount of invisible matter—dark matter—whose gravity holds them together. We cannot see it directly because it does not emit or reflect light, but we can detect its gravitational effects.\n\nDark energy addresses a different mystery. In the late twentieth century, astronomers made a startling discovery: the expansion of the universe is not slowing down, as gravity would suggest, but speeding up. Something appears to be pushing the universe apart, overcoming the inward pull of gravity on the largest scales. Scientists gave this unknown force the name dark energy, though naming it is not the same as understanding it.\n\nWhat makes these ideas so remarkable—and so humbling—is their scale. Current estimates suggest that ordinary matter makes up only about five percent of the universe, dark matter about twenty-seven percent, and dark energy the remaining sixty-eight percent. In other words, roughly ninety-five percent of the universe is made of things we cannot see and do not yet understand. Rather than a sign of failure, many scientists see this as thrilling: it means that some of the most fundamental features of reality are still waiting to be discovered.`,
    items: [{ id: 't20-r-ap1', answer: 0 }, { id: 't20-r-ap2', answer: 1 }, { id: 't20-r-ap3', answer: 2 }, { id: 't20-r-ap4', answer: 3 }, { id: 't20-r-ap5', answer: 0 }, { id: 't20-r-ap6', answers: ['A', 'C'] }],
  },
] as const;
